# Scientific-Conclusion Stability under Catalog-Source Substitution

**Protocol 2.4: exact finite-source certificates for exoplanet-derived quantities and
transit-only operational rankings**

This notebook compares two frozen, analysis-ready exoplanet datasets without treating
either source as ground truth. It asks whether derived physical conclusions remain stable
when source values are substituted. The primary endpoint is the geometric planet-to-star
area ratio. A separate operational endpoint ranks only systems classified as transit-related
in both datasets.

**Protocol version:** 2.4.0  
**Protocol date:** 14 August 2026  
**Author:** Khaled Tarchi  
**Review mode:** Solo-author self-audit  
**Primary estimand:** exact finite-source width of geometric area ratio  
**Operational estimand:** guaranteed/possible/excluded top-25 membership among concordant transits

## Estimands and interpretation

For positive source values $x_{j,A}$ and $x_{j,B}$ and a monomial observable
$f(x)=C\prod_j x_j^{\alpha_j}$, this notebook distinguishes:

1. **complete-row substitution**, comparing $f_A$ with $f_B$;
2. **coordinate-wise source-factorial substitution**, evaluating every A/B input vertex;
3. **decision stability**, determining whether threshold or top-$k$ decisions are invariant.

These are exact properties of the two supplied artifacts. The coordinate-wise factorial
interval constitutes a **finite-source sensitivity envelope**---the range of derived
values produced by exhaustive A/B substitution at each coordinate. It is not a physical
uncertainty interval, not a confidence or credible interval for the unknown true planet,
and does not identify which source is more accurate.

## Exact-bound proposition

Let $\ell_j=\min(\log x_{j,A},\log x_{j,B})$ and
$u_j=\max(\log x_{j,A},\log x_{j,B})$. For a positive monomial,

$$
\log f_{\min}=\log C+\sum_{\alpha_j\ge0}\alpha_j\ell_j
  +\sum_{\alpha_j<0}\alpha_j u_j,
$$
$$
\log f_{\max}=\log C+\sum_{\alpha_j\ge0}\alpha_j u_j
  +\sum_{\alpha_j<0}\alpha_j\ell_j.
$$

Therefore
$$
\log(f_{\max}/f_{\min})=
\sum_j |\alpha_j|\,|\log(x_{j,A}/x_{j,B})|.
$$

The implementation verifies this result by enumerating every source vertex for every
eligible row and every observable.

## Pre-analysis commitments

- No primary value is imputed, clipped, winsorized, or silently discarded. Documented pre-analysis corrections (e.g. unit errors) are permitted when supported by published references and recorded in the corrections ledger.
- Matching is conservative, one-to-one, and computationally audited. Host-key and component concordance are reported as diagnostics but are not required for Tier-1.
- Orbital period is a matching-consistency diagnostic, not an independent negative control.
- The general primary cohort and transit-only operational cohort are reported separately.
- Mass-dependent observables remain secondary because mass semantics may differ.
- Exact descriptive results are primary; host resampling is composition sensitivity only.
- Extreme discrepancies are retained and automatically selected for forensic reporting.
- No causal, habitability, catalogue-quality, or truth-ranking claim is permitted.

## Certification and submission-readiness contract

The notebook reports separate states. **Computational certification** covers executable
mathematics, validation, ranking logic, and artifact integrity. **Scientific clearance**
additionally requires documented review of every priority-0 case; in this single-author
project the lead author (Khaled Tarchi) performs that review as a self-audit. **External
submission readiness** would further require complete input provenance, a clean-environment
reproduction attestation certified by the lead author as a solo-author self-audit, and
an external independent reproduction. The final package audit is complete. External independent reproduction has not yet been performed and is not claimed. Placeholder or draft identity text in any provenance,
reproduction, or review record is rejected as blocking. Missing documentation is reported
as `not_assessed`; it is never converted into a fabricated pass or an implied scientific
finding.

## Corrigendum: K2-136 d unit correction (protocol 2.4.0)

The raw Source A snapshot (`prism-uploads/kepler.csv`, sha256 `74b9c7ae...`) contained a
unit error for **K2-136 d**: its radius was entered as `1.450 R_Jup` although the underlying
source value is `1.450 R_earth` (Mann et al. 2018). Interpreted as Jupiter radii it produced
the largest substitution width in the raw baseline (factorial width ~113.48, rank_a 2,
rank_b 1380, rank displacement 1378) and was the only `unit_error` forensic finding.

Corrected snapshot (sha256 `c945f9a5...`):
- radius: `1.450 R_Jup` -> `0.1293603354 R_Jup` (= `1.450 R_earth` / R_JUPITER_TO_R_EARTH=11.209);
- radius error bars: `0.080/0.110 R_Jup` -> `0.0071371220/0.0098135427 R_Jup`
  (= `0.080/0.110 R_earth`, matching Mann et al. 2018 `1.45_{-0.08}^{+0.11} R_earth`);
- every other row and column is byte-identical to the raw snapshot.

After correction the primary maximum factorial width falls from ~113.48 to **13.57**
(`hats-12 b`, rank displacement 85). K2-136 d is no longer an extreme case and is absent
from the forensic table. The operational robust pool holds **44** concordant transits
(13 guaranteed, 31 possible top-25 members), and all 113 priority-0 cases received documented review. Of these, 105 were
classified as confirmed source differences and eight as confirmed agreements. This corrigendum is
recorded under `source_a.derivative_status` and `source_a.preprocessing_history` in
`source_provenance.json`.

## Discussion: K2-136 d — historical versus composite radius

After the unit correction (see corrigendum above), the two frozen sources still differ on
the radius of **K2-136 d**: `1.450 R_earth` (Source A, historical, Mann et al. 2018) versus
`1.565 R_earth` (Source B, NASA composite). The relative difference is about **7.9%**
(`1.565 / 1.450 - 1`).

This is a genuine catalog-version and measurement-epoch difference, not a second unit error.
The two sources differ not only in catalog curation policies but also in publication epoch:
Source A extends to approximately February 2018, whereas Source B is frozen in March 2026.
Observed discrepancies therefore combine curation decisions and temporal updates:

- Source A preserves the historical published value `1.45_{-0.08}^{+0.11} R_earth`
  (Mann et al. 2018);
- Source B reports the NASA Exoplanet Archive composite value `1.565 R_earth`.

The protocol 2.4.0 corrigendum corrected only the Source A *unit encoding*
(`1.450 R_Jup` -> `0.1293603354 R_Jup`) without altering the historical value, so the
remaining discrepancy is retained as a `confirmed_source_difference` and requires no second
correction. K2-136 d remains concordant under the operational transit-evidence criterion;
its radius difference contributes to the primary geometric-width distribution and is
subject to the same forensic case-selection rules as every other matched system.

**Source-date confounding:** the comparison confounds catalog curation differences with the ~8-year information-epoch gap (Source A ~February 2018, Source B March 2026). Disentangling these two effects would require access to same-epoch catalog versions, which is outside the scope of this finite-source analysis. Readers should interpret all observed discrepancies as combining both sources of variation.

## Discussion: aggregate agreement versus tail rank displacement

The two-source ranking of the `N = 2,561` concordant-transit geometric signal values shows
high aggregate agreement: Kendall tau `0.9765`, Spearman rho `0.9967`, median rank
displacement `5.0`, 95th percentile `77.0`, 99th percentile `250.4`.

The tail is far larger than the aggregate suggests: the **maximum rank displacement is
`1,115`** positions. Within the operational top-25 pool the largest displacement is `243`
(`hat-p-67 b`), so the extreme `1,115`-place movement occurs below the top-25 boundary. The
top-25 sets overlap in `21 / 29` members (Jaccard `0.724`), giving a robust pool of `44`
(`13` guaranteed, `31` possible).

Interpretation: aggregate agreement statistics compress the extreme cases that the forensic
case-selection procedure is designed to surface. Any ranking-based conclusion must report
both the aggregate coefficients and the tail displacements, and extreme cases must cite the
underlying `confirmed_source_difference` review record rather than a blanket agreement
claim.

## Publication scope, population, and claim contract

**Unit of analysis:** a conservatively matched planet represented in both frozen
derivative source artifacts.  **Primary population:** Tier-1 matches with positive,
finite planet and stellar radii in both sources.  **Operational population:** the
primary population restricted to systems with confirmed transit evidence in both
controlled source vocabularies.

The primary statement concerns the empirical distribution of exact two-source
factorial widths for the geometric planet-to-star area ratio.  The operational
statement concerns guaranteed, possible, and excluded membership in a geometric-
signal top-25 set.  Neither statement estimates truth, measurement uncertainty,
catalog accuracy, transit detectability, atmospheric value, habitability, or causal
effects.  Generalization is restricted to the observed complete-case population;
the notebook quantifies how that population differs from excluded matched systems.
Included systems tend to have shorter periods, smaller semimajor axes, greater
distances, and fainter apparent magnitudes, reflecting transit-survey selection.
The results describe the eligible matched complete-case sub-population, not all
confirmed exoplanets.

A paper may describe the computation as *exact conditional on the two supplied
artifacts*.  It must not describe the entire research project as error-free,
universally valid, or guaranteed to be accepted for publication.

In [1]:
from __future__ import annotations

import copy
import hashlib
import itertools
import json
import math
import platform
import re
import shutil
import sys
import unicodedata
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal, Mapping, Sequence

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
from scipy import stats
import seaborn as sns
import pypdf
from pypdf import PdfReader

try:
    from IPython.display import display
except ImportError:
    def display(*objects: Any) -> None:
        for obj in objects:
            print(obj)

SOFTWARE_VERSIONS = {
    "python": sys.version.split()[0],
    "numpy": np.__version__,
    "pandas": pd.__version__,
    "scipy": scipy.__version__,
    "matplotlib": mpl.__version__,
    "seaborn": sns.__version__,
    "pypdf": pypdf.__version__,
}
display(SOFTWARE_VERSIONS)

{'python': '3.12.10',
 'numpy': '2.0.2',
 'pandas': '2.2.2',
 'scipy': '1.15.3',
 'matplotlib': '3.9.0',
 'seaborn': '0.13.2',
 'pypdf': '6.1.1'}

In [2]:
SEED = 20260813
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 180)
pd.set_option("display.max_colwidth", 120)
sns.set_theme(context="paper", style="whitegrid", palette="colorblind")
mpl.rcParams.update({
    "figure.dpi": 120,
    "savefig.dpi": 300,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "axes.formatter.useoffset": False,
})
print(f"Deterministic analysis seed: {SEED}")

Deterministic analysis seed: 20260813

In [3]:
Severity = Literal["information", "minor", "major", "blocking"]
ReviewFindingStatus = Literal["not_assessed", "acceptable", "correction_required"]

PLACEHOLDER_TERMS: tuple[str, ...] = (
    "placeholder", "example", "test", "unknown", "tbd", "todo",
    "sample text", "replace with", "your name", "your affiliation", "lorem",
)
SOLO_AUTHOR_SENTINEL: str = "N/A (Solo-Author Project)"


def contains_placeholder(text: object) -> bool:
    """Return True when text carries a placeholder identity marker."""
    folded = str(text).strip().casefold()
    if not folded:
        return False
    return any(term in folded for term in PLACEHOLDER_TERMS)


def author_mode_label() -> str:
    """Return the review-mode label enforced by this notebook run."""
    return "solo_author_self_audit" if CONFIG.is_solo_author else "independent_reviewers"


@dataclass(frozen=True)
class AnalysisPaths:
    input_a: Path = Path("prism-uploads/kepler.csv")
    input_b: Path = Path("prism-uploads/nasa_exoplanet_intelligence.csv")
    output_root: Path = Path("publication_artifacts")
    forensic_review_input: Path = Path("prism-uploads/forensic_review_decisions.csv")
    match_review_input: Path = Path("prism-uploads/match_review_decisions.csv")
    provenance_input: Path = Path("prism-uploads/source_provenance.json")
    reproduction_input: Path = Path("prism-uploads/clean_environment_self_reproduction.json")

    @property
    def artifact_dir(self) -> Path:
        return self.output_root / "artifacts"

    @property
    def figure_dir(self) -> Path:
        return self.output_root / "figures"

    @property
    def table_dir(self) -> Path:
        return self.output_root / "tables"

    @property
    def staging_dir(self) -> Path:
        return self.output_root / ".staging"

    def validate(self) -> None:
        values = [
            self.input_a, self.input_b, self.output_root, self.forensic_review_input,
            self.match_review_input, self.provenance_input, self.reproduction_input,
        ]
        for path in values:
            if path.is_absolute() or ".." in path.parts:
                raise ValueError(f"All paths must be safe and relative: {path}")
        if self.output_root in {self.input_a, self.input_b}:
            raise ValueError("Output path cannot overwrite an input file.")


@dataclass(frozen=True)
class AnalysisConfig:
    protocol_version: str = "2.4.0"
    protocol_date: str = "2026-08-14"
    seed: int = SEED
    primary_k: int = 25
    tier1_period_relative_tolerance: float = 1e-3
    tier2_period_relative_tolerance: float = 1e-2
    minimum_tier1_matches: int = 100
    minimum_primary_cohort: int = 100
    minimum_operational_cohort: int = 50
    equivalence_factors: tuple[float, ...] = (1.01, 1.05, 1.10, 1.25, 1.50, 2.0, 5.0, 10.0)
    k_grid: tuple[int, ...] = (5, 10, 25, 50, 75, 100)
    composition_resamples: int = 10_000
    composition_interval_level: float = 0.95
    extreme_width_threshold: float = 2.0
    extreme_rank_displacement: int = 100
    floating_tolerance: float = 1e-11
    figure_format: str = "pdf"
    figure_dpi: int = 300
    allow_output_replacement: bool = False
    bound_property_trials: int = 250
    ranking_property_trials: int = 75
    is_solo_author: bool = True
    lead_author: str = "Khaled Tarchi"


@dataclass(frozen=True)
class ColumnSpec:
    canonical_name: str
    source_name: str
    source_unit: str
    canonical_unit: str
    conversion_factor: float = 1.0
    positive: bool = False
    minimum: float | None = None
    maximum: float | None = None
    semantic_note: str = ""


@dataclass(frozen=True)
class DatasetSchema:
    label: str
    planet_name_column: str
    host_name_column: str
    discovery_method_column: str
    columns: tuple[ColumnSpec, ...]


@dataclass(frozen=True)
class DetectionRule:
    normalized_label: str
    discovery_family: str
    transit_evidence: str
    justification: str


@dataclass(frozen=True)
class PhysicalObservable:
    name: str
    display_name: str
    unit: str
    inputs: tuple[str, ...]
    exponents: tuple[float, ...]
    constant: float
    analysis_status: str
    interpretation: str
    limitations: str


@dataclass(frozen=True)
class ValidationIssue:
    severity: Severity
    code: str
    message: str
    count: int | None = None
    context: Mapping[str, Any] = field(default_factory=dict)


@dataclass
class ValidationReport:
    stage: str
    issues: list[ValidationIssue] = field(default_factory=list)
    metrics: dict[str, int | float | str | bool] = field(default_factory=dict)

    def add(self, severity: Severity, code: str, message: str, count: int | None = None, **context: Any) -> None:
        self.issues.append(ValidationIssue(severity, code, message, count, context))

    @property
    def passed(self) -> bool:
        return not any(issue.severity == "blocking" for issue in self.issues)

    @property
    def blocking_count(self) -> int:
        return sum(issue.severity == "blocking" for issue in self.issues)

    @property
    def major_count(self) -> int:
        return sum(issue.severity == "major" for issue in self.issues)

    @property
    def status(self) -> str:
        if self.blocking_count:
            return "failed"
        if self.major_count:
            return "action_required"
        if self.issues:
            return "passed_with_warnings"
        return "passed"

In [4]:
PATHS = AnalysisPaths()
PATHS.validate()
CONFIG = AnalysisConfig()

R_EARTH_OVER_R_SUN = 0.0091577
M_JUPITER_TO_M_EARTH = 317.828
R_JUPITER_TO_R_EARTH = 11.209
EARTH_DENSITY_G_CM3 = 5.514
EARTH_ESCAPE_VELOCITY_KM_S = 11.186
T_SUN_K = 5772.0

SCHEMA_A = DatasetSchema(
    "Exoplanet.eu Kaggle snapshot", "# name", "star_name", "detection_type",
    (
        ColumnSpec("planet_radius_rearth", "radius", "R_jupiter", "R_earth", R_JUPITER_TO_R_EARTH, True),
        ColumnSpec("planet_mass_mearth", "mass", "M_jupiter", "M_earth", M_JUPITER_TO_M_EARTH, True, semantic_note="true-mass field; mass_sini excluded"),
        ColumnSpec("period_days", "orbital_period", "day", "day", positive=True),
        ColumnSpec("semi_major_axis_au", "semi_major_axis", "au", "au", positive=True),
        ColumnSpec("star_temperature_k", "star_teff", "K", "K", positive=True, minimum=1000, maximum=100000),
        ColumnSpec("star_radius_rsun", "star_radius", "R_sun", "R_sun", positive=True),
        ColumnSpec("star_mass_msun", "star_mass", "M_sun", "M_sun", positive=True),
        ColumnSpec("distance_pc", "star_distance", "pc", "pc", positive=True),
        ColumnSpec("visual_magnitude_mag", "mag_v", "mag", "mag"),
        ColumnSpec("eccentricity", "eccentricity", "", "", minimum=0, maximum=0.999999),
    ),
)

SCHEMA_B = DatasetSchema(
    "NASA-derived Kaggle snapshot", "planet_name", "host_star", "discovery_method",
    (
        ColumnSpec("planet_radius_rearth", "planet_radius_earth", "R_earth", "R_earth", positive=True),
        ColumnSpec("planet_mass_mearth", "planet_mass_earth", "M_earth", "M_earth", positive=True, semantic_note="best-mass provenance unavailable in derivative table"),
        ColumnSpec("period_days", "orbital_period_days", "day", "day", positive=True),
        ColumnSpec("semi_major_axis_au", "semi_major_axis_au", "au", "au", positive=True),
        ColumnSpec("star_temperature_k", "star_temp_k", "K", "K", positive=True, minimum=1000, maximum=100000),
        ColumnSpec("star_radius_rsun", "star_radius_sun", "R_sun", "R_sun", positive=True),
        ColumnSpec("star_mass_msun", "star_mass_sun", "M_sun", "M_sun", positive=True),
        ColumnSpec("distance_pc", "dist_from_earth_pc", "pc", "pc", positive=True),
        ColumnSpec("visual_magnitude_mag", "star_vmag", "mag", "mag"),
        ColumnSpec("eccentricity", "orbital_eccentricity", "", "", minimum=0, maximum=0.999999),
    ),
)

OBSERVABLES = {
    "geometric_area_ratio_ppm": PhysicalObservable(
        "geometric_area_ratio_ppm", "Geometric planet-to-star area ratio", "ppm",
        ("planet_radius_rearth", "star_radius_rsun"), (2.0, -2.0),
        R_EARTH_OVER_R_SUN ** 2 * 1e6, "primary",
        "Geometric area ratio; equals idealized undiluted central transit depth only under simplifying assumptions.",
        "Not an observed depth or complete follow-up-priority metric.",
    ),
    "density_g_cm3": PhysicalObservable(
        "density_g_cm3", "Bulk density", "g cm^-3",
        ("planet_mass_mearth", "planet_radius_rearth"), (1.0, -3.0), EARTH_DENSITY_G_CM3,
        "secondary", "Spherical bulk density.", "Mass semantics and provenance may differ between derivative products.",
    ),
    "gravity_gearth": PhysicalObservable(
        "gravity_gearth", "Surface gravity", "g_earth",
        ("planet_mass_mearth", "planet_radius_rearth"), (1.0, -2.0), 1.0,
        "secondary", "Newtonian spherical surface gravity.", "Mass provenance caveat applies.",
    ),
    "escape_velocity_km_s": PhysicalObservable(
        "escape_velocity_km_s", "Escape velocity", "km s^-1",
        ("planet_mass_mearth", "planet_radius_rearth"), (0.5, -0.5), EARTH_ESCAPE_VELOCITY_KM_S,
        "secondary", "Spherical two-body escape velocity.", "Mass provenance caveat applies.",
    ),
    "insolation_searth": PhysicalObservable(
        "insolation_searth", "Incident stellar flux", "S_earth",
        ("star_radius_rsun", "star_temperature_k", "semi_major_axis_au"), (2.0, 4.0, -2.0), T_SUN_K ** -4,
        "secondary", "Blackbody luminosity scaling.", "Does not model spectral or orbital-time variability.",
    ),
}

# Exact, reviewable vocabulary. New labels are blocking until explicitly classified.
# ``transit_evidence`` governs the operational cohort; discovery family alone never does.
DETECTION_RULES: dict[str, DetectionRule] = {
    label: DetectionRule(label, family, evidence, justification)
    for label, family, evidence, justification in (
        ("astrometry", "astrometry", "absent", "Astrometric discovery is not transit evidence."),
        ("disk kinematics", "other", "absent", "Disk-kinematic discovery is not transit evidence."),
        ("eclipse timing variations", "timing", "unresolved", "Eclipse timing alone does not certify a planetary transit."),
        ("imaging", "imaging", "absent", "Direct imaging is not transit evidence."),
        ("microlensing", "microlensing", "absent", "Microlensing is not transit evidence."),
        ("orbital brightness modulation", "other", "unresolved", "Photometric modulation is insufficient for confirmed transit status."),
        ("other", "other", "unresolved", "The source label has no controlled transit interpretation."),
        ("primary transit", "transit", "confirmed", "The source explicitly identifies primary-transit discovery."),
        ("primary transit, ttv", "transit", "confirmed", "Primary-transit evidence is explicit; TTV is additional."),
        ("pulsar", "timing", "absent", "Pulsar discovery is timing based, not transit based."),
        ("pulsar timing", "timing", "absent", "Pulsar timing is not transit evidence."),
        ("pulsation timing variations", "timing", "absent", "Pulsation timing is not transit evidence."),
        ("radial velocity", "radial_velocity", "absent", "Radial velocity is not transit evidence."),
        ("transit", "transit", "confirmed", "The source explicitly identifies transit discovery."),
        ("transit timing variations", "timing", "confirmed", "The source label explicitly states transit timing variations."),
        ("ttv", "timing", "supported", "The abbreviation alone supports but does not independently certify transit status."),
    )
}
display(pd.DataFrame([asdict(value) for value in OBSERVABLES.values()]))

,name,display_name,unit,inputs,exponents,constant,analysis_status,interpretation,limitations
0,geometric_area_ratio_ppm,Geometric planet-to-star area ratio,ppm,"(planet_radius_rearth, star_radius_rsun)","(2.0, -2.0)",8.386347e+01,primary,Geometric area ratio; equals idealized undiluted central transit depth only under simplifying assumptions.,Not an observed depth or complete follow-up-priority metric.
1,density_g_cm3,Bulk density,g cm^-3,"(planet_mass_mearth, planet_radius_rearth)","(1.0, -3.0)",5.514000e+00,secondary,Spherical bulk density.,Mass semantics and provenance may differ between derivative products.
2,gravity_gearth,Surface gravity,g_earth,"(planet_mass_mearth, planet_radius_rearth)","(1.0, -2.0)",1.000000e+00,secondary,Newtonian spherical surface gravity.,Mass provenance caveat applies.
3,escape_velocity_km_s,Escape velocity,km s^-1,"(planet_mass_mearth, planet_radius_rearth)","(0.5, -0.5)",1.118600e+01,secondary,Spherical two-body escape velocity.,Mass provenance caveat applies.
4,insolation_searth,Incident stellar flux,S_earth,"(star_radius_rsun, star_temperature_k, semi_major_axis_au)","(2.0, 4.0, -2.0)",9.009376e-16,secondary,Blackbody luminosity scaling.,Does not model spectral or orbital-time variability.

In [5]:
GENERATOR_PATH = Path("build_research_notebook.py")
GENERATED_NOTEBOOK_PATH = Path("source_substitution_stability.ipynb")

PUBLICATION_CONTRACT = {
    "protocol_version": CONFIG.protocol_version,
    "protocol_date": CONFIG.protocol_date,
    "unit_of_analysis": "conservatively matched planet",
    "primary_population": "Tier-1 matched complete cases for both radii",
    "operational_population": "primary population with confirmed transit evidence in both sources",
    "primary_estimand": "exact finite-source factorial width of geometric area ratio",
    "operational_estimand": "guaranteed/possible/excluded geometric-signal top-25 membership",
    "required_external_certificates": [
        "complete source provenance",
        "completed priority-0 forensic review (solo-author self-audit)",
        "clean-environment reproduction certification (solo-author self-audit)",
    ],
    "prohibited_claims": [
        "either source is ground truth",
        "factorial bounds are confidence or credible intervals",
        "geometric area ratio is an observed transit depth",
        "geometric top-25 membership is a mission target list",
        "results establish causality, habitability, or universal catalog quality",
    ],
}
display(pd.DataFrame({"publication_contract": PUBLICATION_CONTRACT.keys(), "value": PUBLICATION_CONTRACT.values()}))

             publication_contract                                                                                                                    value
0                protocol_version                                                                                                                    2.4.0
1                   protocol_date                                                                                                               2026-08-14
2                unit_of_analysis                                                                                            conservatively matched planet
3              primary_population                                                                             Tier-1 matched complete cases for both radii
4          operational_population                                                       primary population with confirmed transit evidence in both sources
5                primary_estimand                                                              exact finite-source factorial width of geometric area ratio
6            operational_estimand                                                          guaranteed/possible/excluded geometric-signal top-25 membership
7  required_external_certificates  [complete source provenance, completed priority-0 forensic review (solo-author self-audit), clean-environment reprod...
8               prohibited_claims  [either source is ground truth, factorial bounds are confidence or credible intervals, geometric area ratio is an ob...

## Auditable software layer

The following cells define pure transformations and validation functions. They produce no
scientific result until the frozen input files are loaded.

In [6]:
def sha256_file(path: Path) -> str:
    """sha256_file()."""
    if not path.is_file():
        raise FileNotFoundError(path)
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def json_default(value: Any) -> Any:
    """json_default()."""
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    if isinstance(value, Path):
        return value.as_posix()
    if isinstance(value, (tuple, set)):
        return list(value)
    raise TypeError(f"Unsupported JSON value: {type(value)!r}")


def sanitize_json(value: Any) -> Any:
    """sanitize_json()."""
    if isinstance(value, Mapping):
        return {str(key): sanitize_json(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [sanitize_json(item) for item in value]
    if isinstance(value, (float, np.floating)) and not math.isfinite(float(value)):
        return None
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    return value


def prepare_output_directories(paths: AnalysisPaths, allow_replacement: bool) -> None:
    """prepare_output_directories()."""
    paths.validate()
    if paths.output_root.exists() and any(paths.output_root.rglob("*")) and not allow_replacement:
        raise FileExistsError(
            f"Definitive output directory is not empty: {paths.output_root}. "
            "Archive or remove it before a clean publication run."
        )
    for directory in (paths.artifact_dir, paths.figure_dir, paths.table_dir, paths.staging_dir):
        directory.mkdir(parents=True, exist_ok=True)


def atomic_json(payload: Mapping[str, Any], path: Path) -> None:
    """atomic_json()."""
    text = json.dumps(sanitize_json(payload), indent=2, sort_keys=True, allow_nan=False, default=json_default) + "\n"
    temporary = PATHS.staging_dir / f"{path.name}.tmp"
    temporary.write_text(text, encoding="utf-8", newline="\n")
    temporary.replace(path)


def atomic_csv(frame: pd.DataFrame, path: Path, *, gzip: bool = False) -> None:
    """atomic_csv()."""
    if frame.columns.duplicated().any():
        raise ValueError(f"Duplicate columns in export: {path}")
    temporary = PATHS.staging_dir / f"{path.name}.tmp"
    compression: Any = {"method": "gzip", "compresslevel": 9, "mtime": 0} if gzip else None
    frame.to_csv(temporary, index=False, compression=compression, encoding="utf-8", lineterminator="\n")
    temporary.replace(path)


def save_figure(fig: mpl.figure.Figure, stem: str) -> Path:
    """save_figure()."""
    path = PATHS.figure_dir / f"{stem}.{CONFIG.figure_format}"
    temporary = PATHS.staging_dir / f"{stem}.{CONFIG.figure_format}"
    fig.savefig(temporary, dpi=CONFIG.figure_dpi, bbox_inches="tight", metadata={"Title": stem, "Author": "Protocol 2.4 source-substitution study"})
    plt.close(fig)
    if not temporary.is_file() or temporary.stat().st_size == 0:
        raise RuntimeError(f"Figure export failed: {stem}")
    temporary.replace(path)
    reader = PdfReader(path)
    if len(reader.pages) != 1:
        raise RuntimeError(f"Figure must contain exactly one PDF page: {path}")
    media_box = reader.pages[0].mediabox
    if float(media_box.width) <= 0 or float(media_box.height) <= 0:
        raise RuntimeError(f"Figure has an invalid PDF media box: {path}")
    return path


def stable_sort(frame: pd.DataFrame, columns: Sequence[str]) -> pd.DataFrame:
    """stable_sort()."""
    return frame.sort_values(list(columns), kind="mergesort", na_position="last").reset_index(drop=True)


def load_optional_json(path: Path) -> dict[str, Any] | None:
    """load_optional_json()."""
    if not path.is_file():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Optional JSON input must contain an object: {path}")
    return payload


def optional_file_record(path: Path) -> dict[str, Any] | None:
    """optional_file_record()."""
    if not path.is_file():
        return None
    return {"path": path.as_posix(), "sha256": sha256_file(path), "bytes": path.stat().st_size}


prepare_output_directories(PATHS, CONFIG.allow_output_replacement)

In [7]:
def normalize_identifier(value: Any) -> str | None:
    """normalize_identifier()."""
    if value is None or pd.isna(value):
        return None
    text = unicodedata.normalize("NFKC", str(value)).strip().casefold()
    text = text.replace("−", "-").replace("–", "-").replace("—", "-")
    text = re.sub(r"\s*-\s*", "-", text)
    text = re.sub(r"\s+", " ", text)
    return text or None


def extract_planet_component(value: Any) -> str | None:
    """extract_planet_component()."""
    key = normalize_identifier(value)
    if key is None:
        return None
    match = re.search(r"(?:\s|\d)([b-z])$", key)
    return match.group(1) if match else None


def detection_rule(value: Any) -> DetectionRule:
    """detection_rule()."""
    key = normalize_identifier(value)
    if key is None:
        return DetectionRule("missing", "missing", "missing", "Source value is missing.")
    if key not in DETECTION_RULES:
        raise ValueError(f"Unreviewed discovery-method label: {value!r}")
    return DETECTION_RULES[key]


def standardize_detection_method(value: Any) -> str:
    """standardize_detection_method()."""
    return detection_rule(value).discovery_family


def standardize_transit_evidence(value: Any) -> str:
    """standardize_transit_evidence()."""
    return detection_rule(value).transit_evidence


def transit_concordance(evidence_a: pd.Series, evidence_b: pd.Series) -> pd.Series:
    """transit_concordance()."""
    a = evidence_a.eq("confirmed")
    b = evidence_b.eq("confirmed")
    return pd.Series(np.select(
        [a & b, a & ~b, ~a & b, ~a & ~b],
        ["both_transit", "a_transit_only", "b_transit_only", "neither_confirmed_transit"],
        default="unresolved",
    ), index=evidence_a.index, dtype="string")

In [8]:
def load_csv(path: Path) -> pd.DataFrame:
    """load_csv()."""
    if not path.is_file():
        raise FileNotFoundError(f"Required frozen input is missing: {path}")
    frame = pd.read_csv(path, low_memory=False)
    if frame.empty:
        raise ValueError(f"Input is empty: {path}")
    if frame.columns.duplicated().any():
        raise ValueError(f"Input contains duplicate column names: {path}")
    return frame


def audit_raw_schema(frame: pd.DataFrame, schema: DatasetSchema, stage: str) -> ValidationReport:
    """audit_raw_schema()."""
    report = ValidationReport(stage)
    required = {schema.planet_name_column, schema.host_name_column, schema.discovery_method_column}
    required.update(spec.source_name for spec in schema.columns)
    missing = sorted(required - set(frame.columns))
    if missing:
        report.add("blocking", "missing_columns", f"Missing declared columns: {missing}", len(missing))
    report.metrics.update(rows=len(frame), columns=len(frame.columns), duplicate_rows=int(frame.duplicated().sum()))
    if schema.planet_name_column in frame and frame[schema.planet_name_column].isna().any():
        report.add("major", "missing_planet_names", "Planet-name column contains missing values.", int(frame[schema.planet_name_column].isna().sum()))
    return report


def convert_numeric(series: pd.Series, spec: ColumnSpec) -> tuple[pd.Series, pd.Series]:
    """convert_numeric()."""
    numeric = pd.to_numeric(series, errors="coerce")
    invalid = series.notna() & numeric.isna()
    if spec.positive:
        invalid |= numeric.notna() & (numeric <= 0)
    if spec.minimum is not None:
        invalid |= numeric.notna() & (numeric < spec.minimum)
    if spec.maximum is not None:
        invalid |= numeric.notna() & (numeric > spec.maximum)
    canonical = (numeric * spec.conversion_factor).mask(invalid).astype(float)
    return canonical, invalid.astype(bool)


def build_canonical_table(raw: pd.DataFrame, schema: DatasetSchema, source_label: str) -> tuple[pd.DataFrame, ValidationReport]:
    """build_canonical_table()."""
    raw_check = audit_raw_schema(raw, schema, f"raw_schema_{source_label}")
    report = ValidationReport(f"canonicalization_{source_label}")
    if not raw_check.passed:
        report.issues.extend(raw_check.issues)
        return pd.DataFrame(), report
    output = pd.DataFrame(index=raw.index)
    output["source_label"] = source_label
    output["source_row"] = np.arange(len(raw), dtype=int)
    output["planet_name_source"] = raw[schema.planet_name_column].astype("string")
    output["host_name_source"] = raw[schema.host_name_column].astype("string")
    output["planet_key"] = raw[schema.planet_name_column].map(normalize_identifier).astype("string")
    output["host_key"] = raw[schema.host_name_column].map(normalize_identifier).astype("string")
    output["component"] = raw[schema.planet_name_column].map(extract_planet_component).astype("string")
    output["discovery_method_source"] = raw[schema.discovery_method_column].astype("string")
    output["discovery_method_class"] = raw[schema.discovery_method_column].map(standardize_detection_method).astype("string")
    output["transit_evidence"] = raw[schema.discovery_method_column].map(standardize_transit_evidence).astype("string")
    for spec in schema.columns:
        values, invalid = convert_numeric(raw[spec.source_name], spec)
        output[spec.canonical_name] = values
        output[f"{spec.canonical_name}_invalid"] = invalid
        if invalid.any():
            report.add("minor", "invalid_numeric", f"{spec.source_name}: invalid values set to missing.", int(invalid.sum()), column=spec.source_name)
    output["duplicate_planet_key"] = output["planet_key"].duplicated(keep=False) & output["planet_key"].notna()
    report.metrics.update(rows=len(output), columns=len(output.columns))
    report.metrics["missing_planet_key"] = int(output["planet_key"].isna().sum())
    report.metrics["duplicate_planet_key_rows"] = int(output["duplicate_planet_key"].sum())
    return output.reset_index(drop=True), report


def report_table(report: ValidationReport) -> pd.DataFrame:
    """report_table()."""
    return pd.DataFrame({
        "stage": [report.stage], "status": [report.status], "computational_pass": [report.passed],
        "major_count": [report.major_count], "blocking_count": [report.blocking_count],
        "issues": [" | ".join(f"{x.severity}:{x.code}:{x.message}" for x in report.issues)],
        **{key: [value] for key, value in report.metrics.items()},
    })

In [9]:
def generate_name_candidates(canon_a: pd.DataFrame, canon_b: pd.DataFrame) -> pd.DataFrame:
    """generate_name_candidates()."""
    left = canon_a[canon_a["planet_key"].notna()].copy()
    right = canon_b[canon_b["planet_key"].notna()].copy()
    counts_a = left["planet_key"].value_counts()
    counts_b = right["planet_key"].value_counts()
    left["key_count_a"] = left["planet_key"].map(counts_a)
    right["key_count_b"] = right["planet_key"].map(counts_b)
    return left.merge(right, on="planet_key", how="inner", suffixes=("_a", "_b"), validate="many_to_many")


def add_matching_diagnostics(candidates: pd.DataFrame) -> pd.DataFrame:
    """add_matching_diagnostics()."""
    output = candidates.copy()
    pa = pd.to_numeric(output["period_days_a"], errors="coerce")
    pb = pd.to_numeric(output["period_days_b"], errors="coerce")
    available = pa.notna() & pb.notna() & (pa > 0) & (pb > 0)
    output["period_available_both"] = available
    output["period_signed_log_ratio"] = np.nan
    output["period_absolute_log_ratio"] = np.nan
    output["period_relative_difference"] = np.nan
    with np.errstate(divide="raise", invalid="raise", over="raise"):
        signed = np.log(pa[available] / pb[available])
    output.loc[available, "period_signed_log_ratio"] = signed
    output.loc[available, "period_absolute_log_ratio"] = np.abs(signed)
    output.loc[available, "period_relative_difference"] = np.abs(pa[available] - pb[available]) / np.minimum(pa[available], pb[available])
    output["host_key_concordant"] = output["host_key_a"].eq(output["host_key_b"])
    output["component_concordant"] = output["component_a"].eq(output["component_b"]) | output["component_a"].isna() | output["component_b"].isna()
    output["transit_concordance"] = transit_concordance(output["transit_evidence_a"], output["transit_evidence_b"])
    return output


def assign_match_tiers(candidates: pd.DataFrame, config: AnalysisConfig) -> pd.DataFrame:
    """assign_match_tiers()."""
    output = candidates.copy()
    unique = output["key_count_a"].eq(1) & output["key_count_b"].eq(1)
    rel = output["period_relative_difference"]
    output["match_tier_auto"] = "rejected"
    output["match_reason_auto"] = "duplicate_identifier_or_incompatible_period"
    tier1 = unique & output["period_available_both"] & rel.le(config.tier1_period_relative_tolerance)
    tier2 = unique & (~output["period_available_both"] | (rel.gt(config.tier1_period_relative_tolerance) & rel.le(config.tier2_period_relative_tolerance)))
    output.loc[tier1, ["match_tier_auto", "match_reason_auto"]] = ["tier1", "unique_identifier_period_consistent"]
    output.loc[tier2, ["match_tier_auto", "match_reason_auto"]] = ["tier2", "unique_identifier_period_missing_or_looser"]
    return output


def load_match_review_decisions(path: Path) -> pd.DataFrame:
    """load_match_review_decisions()."""
    columns = [
        "source_row_a", "source_row_b", "match_tier", "reason", "reviewer", "review_date",
        "second_reviewer", "adjudication",
    ]
    if not path.is_file():
        return pd.DataFrame(columns=columns)
    decisions = pd.read_csv(path, dtype="string").fillna("")
    missing = set(columns) - set(decisions.columns)
    if missing:
        raise ValueError(f"Match review decisions are missing columns: {sorted(missing)}")
    if decisions.duplicated(["source_row_a", "source_row_b"]).any():
        raise ValueError("Match review decision keys must be unique.")
    for column in ("source_row_a", "source_row_b"):
        numeric = pd.to_numeric(decisions[column], errors="coerce")
        if numeric.isna().any() or (numeric % 1).ne(0).any():
            raise ValueError(f"{column} must contain integer source-row identifiers.")
        decisions[column] = numeric.astype(int)
    if not decisions["match_tier"].isin(["tier1", "tier2", "rejected"]).all():
        raise ValueError("Match review decisions contain an invalid tier.")
    dates = pd.to_datetime(decisions["review_date"], errors="coerce", utc=True)
    if dates.isna().any() or dates.gt(pd.Timestamp.now(tz="UTC")).any():
        raise ValueError("Match review dates must be valid and nonfuture.")
    reviewer_one = decisions["reviewer"].str.strip().str.casefold()
    reviewer_two = decisions["second_reviewer"].str.strip().str.casefold()
    if reviewer_one.eq("").any() or reviewer_two.eq("").any() or reviewer_one.eq(reviewer_two).any():
        raise ValueError("Match decisions require two distinct named reviewers.")
    if decisions["reason"].str.strip().eq("").any() or decisions["adjudication"].str.strip().eq("").any():
        raise ValueError("Match decisions require reasons and adjudications.")
    return decisions[columns].copy()


def apply_manual_decisions(candidates: pd.DataFrame, decisions: pd.DataFrame) -> pd.DataFrame:
    """apply_manual_decisions()."""
    output = candidates.copy()
    output["match_tier"] = output["match_tier_auto"]
    output["match_reason"] = output["match_reason_auto"]
    output["manual_review"] = False
    if decisions.empty:
        return output
    required = {"source_row_a", "source_row_b", "match_tier", "reason", "reviewer", "review_date", "second_reviewer", "adjudication"}
    if not required.issubset(decisions.columns):
        raise ValueError(f"Manual decisions require columns: {sorted(required)}")
    if decisions.duplicated(["source_row_a", "source_row_b"]).any():
        raise ValueError("Manual decision keys must be unique.")
    candidate_keys = set(map(tuple, output[["source_row_a", "source_row_b"]].to_numpy()))
    decision_keys = set(map(tuple, decisions[["source_row_a", "source_row_b"]].to_numpy()))
    unknown = decision_keys - candidate_keys
    if unknown:
        raise ValueError(f"Manual match decisions reference unknown candidates: {sorted(unknown)[:10]}")
    lookup = decisions.set_index(["source_row_a", "source_row_b"])
    for index, row in output.iterrows():
        key = (row["source_row_a"], row["source_row_b"])
        if key in lookup.index:
            decision = lookup.loc[key]
            output.at[index, "match_tier"] = decision["match_tier"]
            output.at[index, "match_reason"] = f"manual:{decision['reason']}"
            output.at[index, "manual_review"] = True
    return output


def finalize_matches(candidates: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """finalize_matches()."""
    audit = stable_sort(candidates, ["planet_key", "source_row_a", "source_row_b"])
    accepted = audit[audit["match_tier"].isin(["tier1", "tier2"])].copy()
    if accepted.duplicated("source_row_a").any() or accepted.duplicated("source_row_b").any():
        raise RuntimeError("Accepted matches are not one-to-one.")
    return audit, accepted.reset_index(drop=True)

In [10]:
def semantic_eligibility(frame: pd.DataFrame, observable: PhysicalObservable, suffix: str) -> pd.Series:
    """semantic_eligibility()."""
    mask = pd.Series(True, index=frame.index)
    for variable in observable.inputs:
        column = f"{variable}{suffix}"
        if column not in frame:
            return pd.Series(False, index=frame.index)
        values = pd.to_numeric(frame[column], errors="coerce")
        mask &= values.notna() & np.isfinite(values) & values.gt(0)
    return mask


def evaluate_monomial(frame: pd.DataFrame, observable: PhysicalObservable, suffix: str) -> pd.Series:
    """evaluate_monomial()."""
    eligible = semantic_eligibility(frame, observable, suffix)
    result = pd.Series(np.nan, index=frame.index, dtype=float)
    if eligible.any():
        log_value = np.full(int(eligible.sum()), math.log(observable.constant), dtype=float)
        with np.errstate(divide="raise", invalid="raise", over="raise"):
            for variable, exponent in zip(observable.inputs, observable.exponents):
                log_value += exponent * np.log(frame.loc[eligible, f"{variable}{suffix}"].to_numpy(float))
            result.loc[eligible] = np.exp(log_value)
    return result


def enumerate_vertices(row: pd.Series, observable: PhysicalObservable) -> np.ndarray:
    """enumerate_vertices()."""
    pairs = [(float(row[f"{name}_a"]), float(row[f"{name}_b"])) for name in observable.inputs]
    values: list[float] = []
    for vertex in itertools.product(*pairs):
        log_value = math.log(observable.constant)
        for value, exponent in zip(vertex, observable.exponents):
            log_value += exponent * math.log(value)
        values.append(math.exp(log_value))
    return np.asarray(values, dtype=float)


def exact_factorial_bounds(frame: pd.DataFrame, observable: PhysicalObservable) -> pd.DataFrame:
    """exact_factorial_bounds()."""
    eligible_a = semantic_eligibility(frame, observable, "_a")
    eligible_b = semantic_eligibility(frame, observable, "_b")
    eligible = eligible_a & eligible_b
    output = pd.DataFrame(index=frame.index)
    output["eligible_a"] = eligible_a
    output["eligible_b"] = eligible_b
    output["eligible_both"] = eligible
    output["source_value_a"] = evaluate_monomial(frame, observable, "_a")
    output["source_value_b"] = evaluate_monomial(frame, observable, "_b")
    output["complete_row_lower"] = np.minimum(output["source_value_a"], output["source_value_b"])
    output["complete_row_upper"] = np.maximum(output["source_value_a"], output["source_value_b"])
    output["complete_row_log_width"] = np.log(output["complete_row_upper"] / output["complete_row_lower"])
    output["factorial_lower"] = np.nan
    output["factorial_upper"] = np.nan
    output["factorial_log_width"] = np.nan
    if eligible.any():
        lower_log = np.full(int(eligible.sum()), math.log(observable.constant))
        upper_log = np.full(int(eligible.sum()), math.log(observable.constant))
        for variable, exponent in zip(observable.inputs, observable.exponents):
            la = np.log(frame.loc[eligible, f"{variable}_a"].to_numpy(float))
            lb = np.log(frame.loc[eligible, f"{variable}_b"].to_numpy(float))
            lo, hi = np.minimum(la, lb), np.maximum(la, lb)
            lower_log += exponent * (lo if exponent >= 0 else hi)
            upper_log += exponent * (hi if exponent >= 0 else lo)
            contribution = pd.Series(np.nan, index=frame.index, dtype=float)
            contribution.loc[eligible] = abs(exponent) * np.abs(la - lb)
            output[f"contribution_{variable}"] = contribution
        output.loc[eligible, "factorial_lower"] = np.exp(lower_log)
        output.loc[eligible, "factorial_upper"] = np.exp(upper_log)
        output.loc[eligible, "factorial_log_width"] = upper_log - lower_log
    output["complete_row_width"] = np.exp(output["complete_row_log_width"])
    output["factorial_width"] = np.exp(output["factorial_log_width"])
    output["factorial_inflation"] = output["factorial_width"] / output["complete_row_width"]
    output["signed_log_ratio"] = np.log(output["source_value_a"] / output["source_value_b"])
    output["absolute_log_ratio"] = output["signed_log_ratio"].abs()
    return output


def build_certificates(matches: pd.DataFrame, observable: PhysicalObservable) -> pd.DataFrame:
    """build_certificates()."""
    bounds = exact_factorial_bounds(matches, observable)
    identity_columns = [
        "planet_key", "planet_name_source_a", "planet_name_source_b", "host_key_a", "host_key_b",
        "source_row_a", "source_row_b", "match_tier", "match_reason", "manual_review",
        "period_relative_difference", "discovery_method_class_a", "discovery_method_class_b",
        "transit_evidence_a", "transit_evidence_b", "transit_concordance",
    ]
    for variable in observable.inputs:
        identity_columns.extend([f"{variable}_a", f"{variable}_b"])
    output = pd.concat([matches[identity_columns].copy(), bounds], axis=1)
    output["observable"] = observable.name
    output["observable_unit"] = observable.unit
    return output


def verify_certificates(certificates: pd.DataFrame, matches: pd.DataFrame, observable: PhysicalObservable, tolerance: float, stage: str | None = None) -> ValidationReport:
    """verify_certificates()."""
    report = ValidationReport(stage or f"certificate_verification:{observable.name}")
    eligible_indices = certificates.index[certificates["eligible_both"]]
    failures = 0
    contribution_columns = [f"contribution_{name}" for name in observable.inputs]
    for index in eligible_indices:
        vertices = enumerate_vertices(matches.loc[index], observable)
        expected = certificates.loc[index, ["factorial_lower", "factorial_upper"]].to_numpy(float)
        if not np.allclose(expected, [vertices.min(), vertices.max()], rtol=tolerance, atol=0):
            failures += 1
    if failures:
        report.add("blocking", "vertex_mismatch", "Analytical and enumerated bounds differ.", failures)
    eligible = certificates.loc[eligible_indices]
    inside = eligible["source_value_a"].between(eligible["factorial_lower"], eligible["factorial_upper"], inclusive="both") & eligible["source_value_b"].between(eligible["factorial_lower"], eligible["factorial_upper"], inclusive="both")
    if not inside.all():
        report.add("blocking", "source_outside_bounds", "A complete-source value lies outside its factorial bounds.", int((~inside).sum()))
    contribution_sum = eligible[contribution_columns].sum(axis=1)
    if not np.allclose(contribution_sum, eligible["factorial_log_width"], rtol=tolerance, atol=tolerance):
        report.add("blocking", "contribution_identity", "Input contributions do not sum to log width.")
    finite_columns = ["source_value_a", "source_value_b", "factorial_lower", "factorial_upper", "factorial_width"]
    if not np.isfinite(eligible[finite_columns].to_numpy(float)).all():
        report.add("blocking", "nonfinite_values", "Eligible certificates contain non-finite values.")
    if (eligible["factorial_lower"] > eligible["factorial_upper"]).any() or (eligible["factorial_width"] < 1).any():
        report.add("blocking", "invalid_order", "Certificate bound ordering failed.")
    if (eligible["factorial_width"] + tolerance < eligible["complete_row_width"]).any():
        report.add("blocking", "factorial_nesting", "Factorial width is smaller than complete-row width.")
    report.metrics.update(eligible_rows=len(eligible_indices), enumerated_rows=len(eligible_indices), failures=failures)
    return report

In [11]:
def add_source_ranks(certificates: pd.DataFrame) -> pd.DataFrame:
    """add_source_ranks()."""
    output = certificates.copy()
    for source in ("a", "b"):
        column = f"source_value_{source}"
        output[f"rank_{source}"] = output[column].rank(method="min", ascending=False, na_option="bottom").astype("Int64")
    output["rank_displacement"] = (output["rank_a"] - output["rank_b"]).abs().astype("Int64")
    return output


def robust_top_k(certificates: pd.DataFrame, k: int) -> pd.DataFrame:
    """robust_top_k()."""
    valid = certificates.dropna(subset=["factorial_lower", "factorial_upper"]).copy()
    lower = valid["factorial_lower"].to_numpy(float)
    upper = valid["factorial_upper"].to_numpy(float)
    sorted_upper = np.sort(upper)
    sorted_lower = np.sort(lower)
    could_outrank = len(valid) - np.searchsorted(sorted_upper, lower, side="right") - (upper > lower).astype(int)
    always_outrank = len(valid) - np.searchsorted(sorted_lower, upper, side="right")
    valid["worst_rank"] = 1 + np.maximum(could_outrank, 0)
    valid["best_rank"] = 1 + always_outrank
    valid["top_k_status"] = np.select(
        [valid["worst_rank"].le(k), valid["best_rank"].le(k)],
        ["guaranteed", "possible"], default="excluded",
    )
    valid["k"] = k
    return stable_sort(valid, ["worst_rank", "best_rank", "planet_key"])


def verify_ranking(ranking: pd.DataFrame, k: int, expected_n: int) -> ValidationReport:
    """verify_ranking()."""
    report = ValidationReport(f"robust_ranking:k={k}")
    valid_status = ranking["top_k_status"].isin(["guaranteed", "possible", "excluded"])
    if len(ranking) != expected_n:
        report.add("blocking", "ranking_size", "Ranking size differs from operational cohort.", len(ranking), expected=expected_n)
    if not valid_status.all():
        report.add("blocking", "invalid_status", "Unknown robust-ranking status.", int((~valid_status).sum()))
    if not ranking.loc[ranking["top_k_status"].eq("guaranteed"), "worst_rank"].le(k).all():
        report.add("blocking", "guarantee_condition", "Guaranteed item violates worst-rank condition.")
    if not ranking.loc[ranking["top_k_status"].eq("excluded"), "best_rank"].gt(k).all():
        report.add("blocking", "exclusion_condition", "Excluded item violates best-rank condition.")
    report.metrics.update(rows=len(ranking), guaranteed=int(ranking["top_k_status"].eq("guaranteed").sum()), possible=int(ranking["top_k_status"].eq("possible").sum()), excluded=int(ranking["top_k_status"].eq("excluded").sum()))
    return report


def ranking_agreement(certificates: pd.DataFrame, k: int) -> dict[str, Any]:
    """ranking_agreement()."""
    valid = certificates.dropna(subset=["source_value_a", "source_value_b"]).copy()
    top_a = set(valid.nlargest(k, "source_value_a")["planet_key"])
    top_b = set(valid.nlargest(k, "source_value_b")["planet_key"])
    intersection, union = top_a & top_b, top_a | top_b
    displacement = valid["rank_displacement"].astype(float)
    return {
        "n_ranking": len(valid),
        "spearman_rho": float(stats.spearmanr(valid["source_value_a"], valid["source_value_b"]).statistic),
        "kendall_tau": float(stats.kendalltau(valid["source_value_a"], valid["source_value_b"]).statistic),
        "top_k_intersection": len(intersection), "top_k_union": len(union),
        "top_k_jaccard": len(intersection) / len(union) if union else float("nan"),
        "median_rank_displacement": float(displacement.median()),
        "p95_rank_displacement": float(displacement.quantile(0.95)),
        "p99_rank_displacement": float(displacement.quantile(0.99)),
        "maximum_rank_displacement": int(displacement.max()),
    }

In [12]:
def summarize_widths(certificates: pd.DataFrame, factors: Sequence[float]) -> dict[str, Any]:
    """summarize_widths()."""
    work = certificates.dropna(subset=["factorial_log_width"]).copy()
    factorial = work["factorial_width"]
    complete = work["complete_row_width"]
    summary: dict[str, Any] = {
        "n_primary": len(work),
        "median_factorial_width": float(factorial.median()),
        "q75_factorial_width": float(factorial.quantile(0.75)),
        "q90_factorial_width": float(factorial.quantile(0.90)),
        "q95_factorial_width": float(factorial.quantile(0.95)),
        "q99_factorial_width": float(factorial.quantile(0.99)),
        "maximum_factorial_width": float(factorial.max()),
        "median_complete_row_width": float(complete.median()),
        "median_factorial_inflation": float(work["factorial_inflation"].median()),
        "q90_factorial_inflation": float(work["factorial_inflation"].quantile(0.90)),
        "q95_factorial_inflation": float(work["factorial_inflation"].quantile(0.95)),
        "q99_factorial_inflation": float(work["factorial_inflation"].quantile(0.99)),
        "maximum_factorial_inflation": float(work["factorial_inflation"].max()),
    }
    for factor in factors:
        label = str(factor).replace(".", "p")
        summary[f"count_factorial_at_or_below_{label}"] = int(factorial.le(factor).sum())
        summary[f"fraction_factorial_at_or_below_{label}"] = float(factorial.le(factor).mean())
        summary[f"count_factorial_above_{label}"] = int(factorial.gt(factor).sum())
        summary[f"fraction_factorial_above_{label}"] = float(factorial.gt(factor).mean())
    for factor in (1.01, 1.05, 1.25, 2.0):
        label = str(factor).replace(".", "p")
        summary[f"fraction_inflation_above_{label}"] = float(work["factorial_inflation"].gt(factor).mean())
    return summary


def threshold_curve(certificates: pd.DataFrame, factors: Sequence[float]) -> pd.DataFrame:
    """threshold_curve()."""
    widths = certificates["factorial_width"].dropna()
    return pd.DataFrame({
        "factor": list(factors),
        "count_at_or_below": [int(widths.le(factor).sum()) for factor in factors],
        "fraction_at_or_below": [float(widths.le(factor).mean()) for factor in factors],
        "count_above": [int(widths.gt(factor).sum()) for factor in factors],
        "fraction_above": [float(widths.gt(factor).mean()) for factor in factors],
        "n_primary": len(widths),
    })


def k_curve(certificates: pd.DataFrame, values: Sequence[int]) -> pd.DataFrame:
    """k_curve()."""
    rows = []
    for k in values:
        ranking = robust_top_k(certificates, k)
        rows.append({
            "k": k,
            "guaranteed": int(ranking["top_k_status"].eq("guaranteed").sum()),
            "possible": int(ranking["top_k_status"].eq("possible").sum()),
            "excluded": int(ranking["top_k_status"].eq("excluded").sum()),
        })
    return pd.DataFrame(rows)


def paired_log_summary(a: pd.Series, b: pd.Series) -> dict[str, Any]:
    """paired_log_summary()."""
    valid = a.notna() & b.notna() & a.gt(0) & b.gt(0)
    logs = np.log(a[valid].to_numpy(float) / b[valid].to_numpy(float))
    if not len(logs):
        return {"n": 0}
    return {
        "n": len(logs), "median_signed_log_ratio": float(np.median(logs)),
        "median_absolute_log_ratio": float(np.median(np.abs(logs))),
        "q05_log_ratio": float(np.quantile(logs, 0.05)), "q95_log_ratio": float(np.quantile(logs, 0.95)),
    }


def host_composition_sensitivity(frame: pd.DataFrame, value_column: str, host_column: str, replicates: int, seed: int) -> pd.Series:
    """host_composition_sensitivity()."""
    work = frame.dropna(subset=[value_column]).copy()
    work[host_column] = work[host_column].fillna(work["planet_key"])
    groups = [group[value_column].to_numpy(float) for _, group in work.groupby(host_column, sort=True)]
    if not groups:
        raise ValueError("No host groups available for composition sensitivity.")
    generator = np.random.default_rng(seed)
    estimates = np.empty(replicates, dtype=float)
    for index in range(replicates):
        selected = generator.integers(0, len(groups), size=len(groups))
        estimates[index] = np.median(np.concatenate([groups[group] for group in selected]))
    return pd.Series(estimates, name="median_factorial_width")


def composition_interval(values: pd.Series, level: float) -> tuple[float, float]:
    """composition_interval()."""
    alpha = 1 - level
    return tuple(np.quantile(values.to_numpy(float), [alpha / 2, 1 - alpha / 2]).tolist())

In [13]:
def select_forensic_cases(primary: pd.DataFrame, operational: pd.DataFrame, secondary: pd.DataFrame, config: AnalysisConfig) -> pd.DataFrame:
    """select_forensic_cases()."""
    operational_fields = operational[["planet_key", "best_rank", "worst_rank", "top_k_status"]].drop_duplicates("planet_key")
    primary_work = primary.drop(columns=["best_rank", "worst_rank", "top_k_status"], errors="ignore").merge(
        operational_fields, on="planet_key", how="left", validate="one_to_one"
    )
    primary_work["selected_primary_extreme"] = (
        primary_work["factorial_width"].ge(config.extreme_width_threshold)
        | primary_work["complete_row_width"].ge(config.extreme_width_threshold)
    )
    primary_work["selected_rank_displacement"] = primary_work["rank_displacement"].astype(float).ge(config.extreme_rank_displacement)
    primary_work["selected_operational_candidate"] = primary_work["top_k_status"].isin(["guaranteed", "possible"])
    stable_keys = set(primary_work.nsmallest(min(10, len(primary_work)), "factorial_width")["planet_key"])
    primary_work["selected_stable_reference"] = primary_work["planet_key"].isin(stable_keys)
    primary_work["selected_secondary_extreme"] = False

    secondary_work = secondary.copy()
    secondary_work["selected_primary_extreme"] = False
    secondary_work["selected_rank_displacement"] = False
    secondary_work["selected_operational_candidate"] = False
    secondary_work["selected_stable_reference"] = False
    secondary_work["selected_secondary_extreme"] = secondary_work["factorial_width"].ge(config.extreme_width_threshold)

    flag_columns = [
        "selected_primary_extreme", "selected_rank_displacement", "selected_operational_candidate",
        "selected_secondary_extreme", "selected_stable_reference",
    ]
    combined = pd.concat([primary_work, secondary_work], ignore_index=True, sort=False)
    combined = combined.loc[combined[flag_columns].any(axis=1)].copy()
    reason_names = {
        "selected_primary_extreme": "primary_extreme",
        "selected_rank_displacement": "rank_displacement",
        "selected_operational_candidate": "operational_candidate",
        "selected_secondary_extreme": "secondary_extreme",
        "selected_stable_reference": "stable_reference",
    }
    combined["selection_reasons"] = combined.apply(
        lambda row: ";".join(reason for column, reason in reason_names.items() if bool(row[column])), axis=1
    )
    combined["review_priority"] = np.select(
        [
            combined["selected_operational_candidate"]
            | combined["factorial_width"].ge(10)
            | combined["rank_displacement"].astype(float).ge(500),
            combined["selected_primary_extreme"] | combined["selected_secondary_extreme"] | combined["selected_rank_displacement"],
            combined["selected_stable_reference"],
        ],
        [0, 1, 3], default=2,
    ).astype(int)
    combined["review_classification"] = "pending"
    combined["review_finding"] = ""
    combined["evidence_reference"] = ""
    combined["reviewer"] = ""
    combined["review_date"] = ""
    combined["second_reviewer"] = ""
    combined["adjudication"] = ""
    return stable_sort(combined, ["review_priority", "factorial_width", "planet_key"])


def load_forensic_review_decisions(path: Path) -> pd.DataFrame:
    """load_forensic_review_decisions()."""
    columns = [
        "planet_key", "observable", "review_classification", "review_finding", "evidence_reference",
        "reviewer", "review_date", "second_reviewer", "adjudication",
    ]
    if not path.is_file():
        return pd.DataFrame(columns=columns)
    decisions = pd.read_csv(path, dtype="string").fillna("")
    missing = set(columns) - set(decisions.columns)
    if missing:
        raise ValueError(f"Forensic review decisions are missing columns: {sorted(missing)}")
    if decisions.duplicated(["planet_key", "observable"]).any():
        raise ValueError("Forensic review decisions must be unique by planet and observable.")
    allowed = {"", "pending", "confirmed_source_difference", "confirmed_agreement", "corrected_source_error", "source_semantic_mismatch", "matching_error", "unit_error", "parameter_semantics_difference", "data_error", "unresolved"}
    invalid = set(decisions["review_classification"].dropna()) - allowed
    if invalid:
        raise ValueError(f"Unknown forensic review classifications: {sorted(invalid)}")
    return decisions[columns].copy()


def apply_forensic_review_decisions(cases: pd.DataFrame, decisions: pd.DataFrame) -> pd.DataFrame:
    """apply_forensic_review_decisions()."""
    if decisions.empty:
        return cases.copy()
    case_keys = set(map(tuple, cases[["planet_key", "observable"]].astype("string").to_numpy()))
    decision_keys = set(map(tuple, decisions[["planet_key", "observable"]].astype("string").to_numpy()))
    unknown = decision_keys - case_keys
    if unknown:
        raise ValueError(f"Forensic review decisions reference unselected cases: {sorted(unknown)[:10]}")
    review_columns = [column for column in decisions.columns if column not in {"planet_key", "observable"}]
    output = cases.drop(columns=review_columns, errors="ignore").merge(
        decisions, on=["planet_key", "observable"], how="left", validate="one_to_one"
    )
    for column in review_columns:
        output[column] = output[column].fillna("")
    output["review_classification"] = output["review_classification"].replace("", "pending")
    return output


def validation_issues_frame(reports: Sequence[ValidationReport]) -> pd.DataFrame:
    """validation_issues_frame()."""
    rows: list[dict[str, Any]] = []
    for report in reports:
        if not report.issues:
            rows.append({"stage": report.stage, "severity": "information", "code": "passed", "message": "No issues.", "count": 0})
        for issue in report.issues:
            rows.append({
                "stage": report.stage, "severity": issue.severity, "code": issue.code,
                "message": issue.message, "count": issue.count,
                "context": json.dumps(dict(issue.context), sort_keys=True, default=json_default),
            })
    return pd.DataFrame(rows)

In [14]:
def run_physics_reference_tests(tolerance: float) -> ValidationReport:
    """run_physics_reference_tests()."""
    report = ValidationReport("physics_reference_tests")
    cases = {
        "geometric_area_ratio_ppm": (R_EARTH_OVER_R_SUN ** 2 * 1e6, 83.863467),
        "density_g_cm3": (EARTH_DENSITY_G_CM3, 5.514),
        "gravity_gearth": (1.0, 1.0),
        "escape_velocity_km_s": (EARTH_ESCAPE_VELOCITY_KM_S, 11.186),
        "insolation_searth": (T_SUN_K ** -4 * T_SUN_K ** 4, 1.0),
    }
    for name, (calculated, expected) in cases.items():
        if not math.isclose(calculated, expected, rel_tol=max(tolerance, 1e-7), abs_tol=1e-9):
            report.add("blocking", "reference_value", f"Known-value test failed for {name}.", calculated=calculated, expected=expected)
    report.metrics["tests"] = len(cases)
    return report


def run_ranking_reference_tests() -> ValidationReport:
    """run_ranking_reference_tests()."""
    report = ValidationReport("ranking_reference_tests")
    point = pd.DataFrame({
        "planet_key": ["a", "b", "c"],
        "factorial_lower": [3.0, 2.0, 1.0],
        "factorial_upper": [3.0, 2.0, 1.0],
    })
    point_result = robust_top_k(point, 1)
    status = dict(zip(point_result["planet_key"], point_result["top_k_status"]))
    if status != {"a": "guaranteed", "b": "excluded", "c": "excluded"}:
        report.add("blocking", "point_ranking", "Point-interval top-1 reference test failed.", status=status)
    overlap = pd.DataFrame({
        "planet_key": ["a", "b"],
        "factorial_lower": [1.0, 1.5],
        "factorial_upper": [3.0, 2.5],
    })
    overlap_result = robust_top_k(overlap, 1)
    if not overlap_result["top_k_status"].eq("possible").all():
        report.add("blocking", "overlap_ranking", "Overlapping-interval reference test failed.")
    tied = pd.DataFrame({
        "planet_key": ["a", "b"],
        "factorial_lower": [2.0, 2.0],
        "factorial_upper": [2.0, 2.0],
    })
    tied_result = robust_top_k(tied, 1)
    if not tied_result["top_k_status"].eq("guaranteed").all():
        report.add("blocking", "tie_policy", "Exact-tie minimum-rank policy failed.")
    report.metrics["tests"] = 3
    return report


def run_contract_reference_tests(tolerance: float) -> ValidationReport:
    """run_contract_reference_tests()."""
    report = ValidationReport("data_contract_reference_tests")
    tests = 0

    identifiers = ["  Kepler–10   b  ", "TOI - 123 b", "Kepler-16 (AB) b"]
    for value in identifiers:
        normalized = normalize_identifier(value)
        tests += 1
        if normalize_identifier(normalized) != normalized:
            report.add("blocking", "normalization_not_idempotent", "Identifier normalization is not idempotent.", value=value)
    tests += 1
    if extract_planet_component("Kepler-10 b") != "b":
        report.add("blocking", "component_not_preserved", "Planet component extraction failed.")

    conversion_cases = [
        (1.0, R_JUPITER_TO_R_EARTH),
        (1.0, M_JUPITER_TO_M_EARTH),
    ]
    for original, factor in conversion_cases:
        tests += 1
        if not math.isclose((original * factor) / factor, original, rel_tol=tolerance, abs_tol=tolerance):
            report.add("blocking", "conversion_roundtrip", "A declared unit conversion failed round-trip validation.", factor=factor)

    tests += 1
    if detection_rule("Eclipse Timing Variations").transit_evidence != "unresolved":
        report.add("blocking", "eclipse_timing_rule", "Eclipse timing was incorrectly promoted to confirmed transit evidence.")
    tests += 1
    if detection_rule("Transit").transit_evidence != "confirmed":
        report.add("blocking", "transit_rule", "Explicit transit evidence was not classified as confirmed.")
    tests += 1
    try:
        detection_rule("Unreviewed Synthetic Discovery Method")
        report.add("blocking", "unknown_detection_rule", "An unknown detection label did not fail closed.")
    except ValueError:
        pass

    observable = OBSERVABLES["geometric_area_ratio_ppm"]
    equal = pd.DataFrame({
        "planet_radius_rearth_a": [1.0], "planet_radius_rearth_b": [1.0],
        "star_radius_rsun_a": [1.0], "star_radius_rsun_b": [1.0],
    })
    equal_bounds_a = exact_factorial_bounds(equal, observable)
    equal_bounds_b = exact_factorial_bounds(equal, observable)
    tests += 1
    if not math.isclose(float(equal_bounds_a.loc[0, "factorial_width"]), 1.0, rel_tol=tolerance, abs_tol=tolerance):
        report.add("blocking", "zero_width_identity", "Identical sources did not produce unit width.")
    tests += 1
    if not equal_bounds_a.equals(equal_bounds_b):
        report.add("blocking", "deterministic_repeat", "Repeated deterministic calculation changed its output.")

    perturbed = equal.copy()
    perturbed["planet_radius_rearth_b"] = 2.0
    perturbed_bounds = exact_factorial_bounds(perturbed, observable)
    tests += 1
    if not math.isclose(float(perturbed_bounds.loc[0, "factorial_width"]), 4.0, rel_tol=tolerance, abs_tol=tolerance):
        report.add("blocking", "single_coordinate_width", "Single-coordinate exponent propagation failed.")

    report.metrics["tests"] = tests
    return report


def run_bound_property_tests(trials: int, seed: int, tolerance: float) -> ValidationReport:
    """run_bound_property_tests()."""
    report = ValidationReport("randomized_bound_property_tests")
    generator = np.random.default_rng(seed)
    failures = 0
    for trial in range(trials):
        n_inputs = int(generator.integers(1, 7))
        inputs = tuple(f"x{index}" for index in range(n_inputs))
        exponents = tuple(generator.uniform(-5, 5, size=n_inputs))
        constant = float(np.exp(generator.uniform(-3, 3)))
        observable = PhysicalObservable(
            f"property_{trial}", "property test", "arbitrary", inputs, exponents, constant,
            "test", "randomized identity test", "not a scientific observable",
        )
        values_a = np.exp(generator.uniform(-12, 12, size=n_inputs))
        values_b = np.exp(generator.uniform(-12, 12, size=n_inputs))
        row = {f"{name}_a": [a] for name, a in zip(inputs, values_a)}
        row.update({f"{name}_b": [b] for name, b in zip(inputs, values_b)})
        frame = pd.DataFrame(row)
        bounds = exact_factorial_bounds(frame, observable).iloc[0]
        vertices = enumerate_vertices(frame.iloc[0], observable)
        if not np.allclose(
            [bounds["factorial_lower"], bounds["factorial_upper"]],
            [vertices.min(), vertices.max()], rtol=tolerance, atol=0,
        ):
            failures += 1
    if failures:
        report.add("blocking", "random_bound_failure", "Randomized exact-bound property test failed.", failures)
    report.metrics.update(trials=trials, failures=failures)
    return report


def run_ranking_property_tests(trials: int, seed: int) -> ValidationReport:
    """run_ranking_property_tests()."""
    report = ValidationReport("randomized_ranking_property_tests")
    generator = np.random.default_rng(seed)
    failures = 0
    for trial in range(trials):
        n = int(generator.integers(2, 8))
        lower = np.exp(generator.uniform(-4, 4, size=n))
        upper = lower * np.exp(generator.uniform(0.01, 2, size=n))
        frame = pd.DataFrame({
            "planet_key": [f"p{index}" for index in range(n)],
            "factorial_lower": lower,
            "factorial_upper": upper,
        })
        calculated = robust_top_k(frame, max(1, n // 2)).set_index("planet_key")
        all_ranks = {key: [] for key in frame["planet_key"]}
        for choices in itertools.product((0, 1), repeat=n):
            values = np.where(np.asarray(choices, dtype=bool), upper, lower)
            ranks = pd.Series(values).rank(method="min", ascending=False).astype(int).to_numpy()
            for key, rank in zip(frame["planet_key"], ranks):
                all_ranks[key].append(int(rank))
        for key, ranks in all_ranks.items():
            if int(calculated.loc[key, "best_rank"]) != min(ranks) or int(calculated.loc[key, "worst_rank"]) != max(ranks):
                failures += 1
                break
    if failures:
        report.add("blocking", "random_ranking_failure", "Randomized endpoint-enumeration ranking test failed.", failures)
    report.metrics.update(trials=trials, failures=failures)
    return report


physics_reference_report = run_physics_reference_tests(CONFIG.floating_tolerance)
ranking_reference_report = run_ranking_reference_tests()
contract_reference_report = run_contract_reference_tests(CONFIG.floating_tolerance)
bound_property_report = run_bound_property_tests(CONFIG.bound_property_trials, CONFIG.seed + 101, CONFIG.floating_tolerance)
ranking_property_report = run_ranking_property_tests(CONFIG.ranking_property_trials, CONFIG.seed + 202)
display(pd.concat([
    report_table(physics_reference_report), report_table(ranking_reference_report),
    report_table(contract_reference_report),
    report_table(bound_property_report), report_table(ranking_property_report),
], ignore_index=True))
if not all(report.passed for report in (physics_reference_report, ranking_reference_report, contract_reference_report, bound_property_report, ranking_property_report)):
    raise RuntimeError("Reference tests failed before empirical analysis.")

                               stage  status  computational_pass  major_count  blocking_count issues  tests  trials  failures
0            physics_reference_tests  passed                True            0               0           5.0     NaN       NaN
1            ranking_reference_tests  passed                True            0               0           3.0     NaN       NaN
2      data_contract_reference_tests  passed                True            0               0          12.0     NaN       NaN
3    randomized_bound_property_tests  passed                True            0               0           NaN   250.0       0.0
4  randomized_ranking_property_tests  passed                True            0               0           NaN    75.0       0.0

## Frozen-input contract

The notebook never downloads or substitutes data. The two original CSV snapshots must exist
at the declared relative paths. The run records their hashes, dimensions, software versions,
and protocol configuration before analysis.

In [15]:
raw_a = load_csv(PATHS.input_a)
raw_b = load_csv(PATHS.input_b)
print(f"Input A: {raw_a.shape}; input B: {raw_b.shape}")

Input A: (3732, 98); input B: (6150, 31)

In [16]:
input_manifest = {
    "protocol_version": CONFIG.protocol_version,
    "protocol_date": CONFIG.protocol_date,
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "software": SOFTWARE_VERSIONS,
    "platform": platform.platform(),
    "config": asdict(CONFIG),
    "inputs": {
        "a": {"path": PATHS.input_a.as_posix(), "sha256": sha256_file(PATHS.input_a), "rows": len(raw_a), "columns": len(raw_a.columns)},
        "b": {"path": PATHS.input_b.as_posix(), "sha256": sha256_file(PATHS.input_b), "rows": len(raw_b), "columns": len(raw_b.columns)},
    },
    "optional_inputs": {
        "forensic_review": optional_file_record(PATHS.forensic_review_input),
        "match_review": optional_file_record(PATHS.match_review_input),
        "source_provenance": optional_file_record(PATHS.provenance_input),
        "clean_environment_self_reproduction": optional_file_record(PATHS.reproduction_input),
    },
    "code_assets": {
        "generator": optional_file_record(GENERATOR_PATH),
    },
    "publication_contract": PUBLICATION_CONTRACT,
}
display(input_manifest)

{'protocol_version': '2.4.0',
 'protocol_date': '2026-08-14',
 'created_utc': '2026-08-21T21:10:19.749781+00:00',
 'software': {'python': '3.12.10',
  'numpy': '2.0.2',
  'pandas': '2.2.2',
  'scipy': '1.15.3',
  'matplotlib': '3.9.0',
  'seaborn': '0.13.2',
  'pypdf': '6.1.1'},
 'platform': 'Windows-10-10.0.19045-SP0',
 'config': {'protocol_version': '2.4.0',
  'protocol_date': '2026-08-14',
  'seed': 20260813,
  'primary_k': 25,
  'tier1_period_relative_tolerance': 0.001,
  'tier2_period_relative_tolerance': 0.01,
  'minimum_tier1_matches': 100,
  'minimum_primary_cohort': 100,
  'minimum_operational_cohort': 50,
  'equivalence_factors': (1.01, 1.05, 1.1, 1.25, 1.5, 2.0, 5.0, 10.0),
  'k_grid': (5, 10, 25, 50, 75, 100),
  'composition_resamples': 10000,
  'composition_interval_level': 0.95,
  'extreme_width_threshold': 2.0,
  'extreme_rank_displacement': 100,
  'floating_tolerance': 1e-11,
  'figure_format': 'pdf',
  'figure_dpi': 300,
  'allow_output_replacement': False,
  'bound_property_trials': 250,
  'ranking_property_trials': 75,
  'is_solo_author': True,
  'lead_author': 'Khaled Tarchi'},
 'inputs': {'a': {'path': 'prism-uploads/kepler.csv',
   'sha256': 'c945f9a5b9f69111add6ccdc7d84dd10b3d42cfe51ce78977148db832beab50e',
   'rows': 3732,
   'columns': 98},
  'b': {'path': 'prism-uploads/nasa_exoplanet_intelligence.csv',
   'sha256': '684d4ae9eaa375a07d50f1f521c4fbbeb3a8cbbe4ec1e0b0598c2dd51f7da287',
   'rows': 6150,
   'columns': 31}},
 'optional_inputs': {'forensic_review': {'path': 'prism-uploads/forensic_review_decisions.csv',
   'sha256': '4b1203dc2a547bac5274697bd61bc0b2f02d9a7ac1fccbc6765c820959b282d9',
   'bytes': 117753},
  'match_review': None,
  'source_provenance': {'path': 'prism-uploads/source_provenance.json',
   'sha256': '5e1937aa0445f706cb4515325128719fd12a427529f95d96ea91679d4a0acbf4',
   'bytes': 6191},
  'clean_environment_self_reproduction': {'path': 'prism-uploads/clean_environment_self_reproduction.json',
   'sha256': '30f44a69d187f95955ce13273f437203e5ef269c574e178b0e7d0f902589d0ff',
   'bytes': 1228}},
 'code_assets': {'generator': {'path': 'build_research_notebook.py',
   'sha256': '3a66ef3f46ba8e630226060cdf91e757538394b017e7d60f7a7a91fcedf1f712',
   'bytes': 70063}},
 'publication_contract': {'protocol_version': '2.4.0',
  'protocol_date': '2026-08-14',
  'unit_of_analysis': 'conservatively matched planet',
  'primary_population': 'Tier-1 matched complete cases for both radii',
  'operational_population': 'primary population with confirmed transit evidence in both sources',
  'primary_estimand': 'exact finite-source factorial width of geometric area ratio',
  'operational_estimand': 'guaranteed/possible/excluded geometric-signal top-25 membership',
  'required_external_certificates': ['complete source provenance',
   'completed priority-0 forensic review (solo-author self-audit)',
   'clean-environment reproduction certification (solo-author self-audit)'],
  'prohibited_claims': ['either source is ground truth',
   'factorial bounds are confidence or credible intervals',
   'geometric area ratio is an observed transit depth',
   'geometric top-25 membership is a mission target list',
   'results establish causality, habitability, or universal catalog quality']}}

In [17]:
provenance_payload = load_optional_json(PATHS.provenance_input)
reproduction_payload = load_optional_json(PATHS.reproduction_input)

provenance_report = ValidationReport("source_provenance")
provenance_required = {"source_a", "source_b"}
provenance_source_fields = {
    "label", "publisher", "acquisition_date", "origin", "license",
    "derivative_status", "preprocessing_history", "sha256",
    "source_version", "persistent_identifier", "citation", "column_semantics",
}
if provenance_payload is None:
    provenance_report.add("major", "provenance_missing", "A complete source-provenance record is required before submission.")
elif not provenance_required.issubset(provenance_payload):
    provenance_report.add("major", "provenance_sections_missing", "Source provenance must document source_a and source_b.")
else:
    for source_key, input_key in (("source_a", "a"), ("source_b", "b")):
        record = provenance_payload[source_key]
        if not isinstance(record, dict) or not provenance_source_fields.issubset(record):
            provenance_report.add("major", "provenance_fields_missing", f"{source_key} has an incomplete provenance record; version, identifier, citation, and column semantics are mandatory.")
            continue
        if str(record["sha256"]) != input_manifest["inputs"][input_key]["sha256"]:
            provenance_report.add("blocking", "provenance_hash_mismatch", f"{source_key} hash does not match the frozen input.")
        acquisition_date = pd.to_datetime(record["acquisition_date"], errors="coerce", utc=True)
        if pd.isna(acquisition_date) or acquisition_date > pd.Timestamp.now(tz="UTC"):
            provenance_report.add("major", "invalid_acquisition_date", f"{source_key} acquisition date is invalid or in the future.")
if provenance_payload is not None:
    for source_key in ("source_a", "source_b"):
        record = provenance_payload.get(source_key)
        if isinstance(record, dict):
            for field_key in ("label", "publisher", "license", "citation", "origin", "source_version", "persistent_identifier", "derivative_status", "preprocessing_history"):
                if field_key in record and contains_placeholder(record[field_key]):
                    provenance_report.add("major", "provenance_placeholder", f"{source_key}.{field_key} contains a placeholder term.")
provenance_documented = provenance_payload is not None and provenance_report.major_count == 0 and provenance_report.passed

reproduction_report = ValidationReport("clean_environment_self_reproduction")
reproduction_required = {
    "protocol_version", "reviewer", "organization", "review_date", "environment",
    "input_a_sha256", "input_b_sha256", "computational_certification_passed",
}
if reproduction_payload is None:
    reproduction_report.add("major", "reproduction_missing", "Clean-environment reproduction (solo-author self-audit) is required before submission.")
elif not reproduction_required.issubset(reproduction_payload):
    reproduction_report.add("major", "reproduction_fields_missing", "Clean-environment reproduction attestation is incomplete.")
else:
    if reproduction_payload["protocol_version"] != CONFIG.protocol_version:
        reproduction_report.add("major", "reproduction_protocol_mismatch", "Reproduction used a different protocol version.")
    if reproduction_payload["input_a_sha256"] != input_manifest["inputs"]["a"]["sha256"] or reproduction_payload["input_b_sha256"] != input_manifest["inputs"]["b"]["sha256"]:
        reproduction_report.add("major", "reproduction_input_mismatch", "Reproduction used different frozen inputs.")
    review_date = pd.to_datetime(reproduction_payload["review_date"], errors="coerce", utc=True)
    if pd.isna(review_date) or review_date > pd.Timestamp.now(tz="UTC"):
        reproduction_report.add("major", "invalid_reproduction_date", "Reproduction date is invalid or in the future.")
    if not bool(reproduction_payload["computational_certification_passed"]):
        reproduction_report.add("major", "reproduction_failed", "Independent reproduction did not pass computational certification.")
    if not str(reproduction_payload["reviewer"]).strip() or not str(reproduction_payload["organization"]).strip() or not str(reproduction_payload["environment"]).strip():
        reproduction_report.add("major", "reproduction_identity_missing", "Reproduction reviewer, organization, and environment are required.")
    for field_key in ("reviewer", "organization", "environment"):
        if contains_placeholder(reproduction_payload[field_key]):
            reproduction_report.add("major", "reproduction_placeholder", f"reproduction.{field_key} contains a placeholder term.")
clean_environment_self_reproduction_passed = reproduction_payload is not None and reproduction_report.major_count == 0 and reproduction_report.passed
if clean_environment_self_reproduction_passed:
    reproduction_report.add(
        "information",
        "self_reproduction_passed",
        "Clean-environment self-reproduction passed in the authoring environment as a solo-author self-audit.",
        is_author=True,
        reproduction_mode="clean_environment_self_reproduction",
        lead_author=CONFIG.lead_author,
    )
display(pd.concat([report_table(provenance_report), report_table(reproduction_report)], ignore_index=True))

,stage,status,computational_pass,major_count,blocking_count,issues
0,source_provenance,passed,True,0,0,
1,clean_environment_self_reproduction,passed_with_warnings,True,0,0,information:self_reproduction_passed:Clean-environment self-reproduction passed in the authoring environment as a so...

In [18]:
raw_report_a = audit_raw_schema(raw_a, SCHEMA_A, "raw_schema_a")
raw_report_b = audit_raw_schema(raw_b, SCHEMA_B, "raw_schema_b")
display(pd.concat([report_table(raw_report_a), report_table(raw_report_b)], ignore_index=True))
if not raw_report_a.passed or not raw_report_b.passed:
    raise RuntimeError("Blocking raw-schema validation failure.")

          stage  status  computational_pass  major_count  blocking_count issues  rows  columns  duplicate_rows
0  raw_schema_a  passed                True            0               0         3732       98               0
1  raw_schema_b  passed                True            0               0         6150       31               0

In [19]:
canon_a, canonical_report_a = build_canonical_table(raw_a, SCHEMA_A, "a")
canon_b, canonical_report_b = build_canonical_table(raw_b, SCHEMA_B, "b")
display(pd.concat([report_table(canonical_report_a), report_table(canonical_report_b)], ignore_index=True))
if not canonical_report_a.passed or not canonical_report_b.passed:
    raise RuntimeError("Blocking canonicalization failure.")

,stage,status,computational_pass,major_count,blocking_count,issues,rows,columns,missing_planet_key,duplicate_planet_key_rows
0,canonicalization_a,passed_with_warnings,True,0,0,minor:invalid_numeric:star_teff: invalid values set to missing. | minor:invalid_numeric:eccentricity: invalid values...,3732,31,0,0
1,canonicalization_b,passed_with_warnings,True,0,0,minor:invalid_numeric:star_temp_k: invalid values set to missing.,6150,31,0,0

In [20]:
canonical_audit = pd.DataFrame({
    "variable": [spec.canonical_name for spec in SCHEMA_A.columns],
    "missing_fraction_a": [float(canon_a[spec.canonical_name].isna().mean()) for spec in SCHEMA_A.columns],
    "missing_fraction_b": [float(canon_b[spec.canonical_name].isna().mean()) for spec in SCHEMA_B.columns],
    "invalid_count_a": [int(canon_a[f"{spec.canonical_name}_invalid"].sum()) for spec in SCHEMA_A.columns],
    "invalid_count_b": [int(canon_b[f"{spec.canonical_name}_invalid"].sum()) for spec in SCHEMA_B.columns],
})
if canon_a["planet_key"].dropna().str.contains(r"\s{2,}", regex=True).any() or canon_b["planet_key"].dropna().str.contains(r"\s{2,}", regex=True).any():
    raise RuntimeError("Identifier normalization left repeated whitespace.")
display(canonical_audit)

               variable  missing_fraction_a  missing_fraction_b  invalid_count_a  invalid_count_b
0  planet_radius_rearth            0.242765            0.008130                0                0
1    planet_mass_mearth            0.575027            0.005041                0                0
2           period_days            0.036710            0.054309                0                0
3    semi_major_axis_au            0.395498            0.051382                0                0
4    star_temperature_k            0.063505            0.047642                8                3
5      star_radius_rsun            0.115220            0.051057                0                0
6        star_mass_msun            0.101286            0.001301                0                0
7           distance_pc            0.307610            0.004390                0                0
8  visual_magnitude_mag            0.592176            0.047967                0                0
9          eccentricity            0.650589            0.152520                1                0

In [21]:
detection_mapping_audit = pd.concat([
    canon_a.groupby(["discovery_method_source", "discovery_method_class", "transit_evidence"], dropna=False).size().rename("n").reset_index().assign(source="a"),
    canon_b.groupby(["discovery_method_source", "discovery_method_class", "transit_evidence"], dropna=False).size().rename("n").reset_index().assign(source="b"),
], ignore_index=True)
detection_mapping_audit = stable_sort(detection_mapping_audit, ["source", "transit_evidence", "discovery_method_class", "discovery_method_source"])
detection_mapping_audit["normalized_label"] = detection_mapping_audit["discovery_method_source"].map(normalize_identifier)
detection_mapping_audit["rule_justification"] = detection_mapping_audit["discovery_method_source"].map(lambda value: detection_rule(value).justification)
if detection_mapping_audit[["discovery_method_class", "transit_evidence"]].isna().any().any():
    raise RuntimeError("Detection-method mapping produced a missing controlled classification.")
if detection_mapping_audit.loc[detection_mapping_audit["transit_evidence"].eq("confirmed"), "discovery_method_class"].eq("other").any():
    raise RuntimeError("Confirmed transit evidence cannot use the generic discovery family.")
display(detection_mapping_audit)

,discovery_method_source,discovery_method_class,transit_evidence,n,source,normalized_label,rule_justification
0,Astrometry,astrometry,absent,1,a,astrometry,Astrometric discovery is not transit evidence.
1,Imaging,imaging,absent,93,a,imaging,Direct imaging is not transit evidence.
2,Microlensing,microlensing,absent,65,a,microlensing,Microlensing is not transit evidence.
3,Radial Velocity,radial_velocity,absent,745,a,radial velocity,Radial velocity is not transit evidence.
4,Pulsar,timing,absent,29,a,pulsar,"Pulsar discovery is timing based, not transit based."
5,Primary Transit,transit,confirmed,2778,a,primary transit,The source explicitly identifies primary-transit discovery.
6,"Primary Transit, TTV",transit,confirmed,2,a,"primary transit, ttv",Primary-transit evidence is explicit; TTV is additional.
7,TTV,timing,supported,5,a,ttv,The abbreviation alone supports but does not independently certify transit status.
8,Other,other,unresolved,14,a,other,The source label has no controlled transit interpretation.
9,Astrometry,astrometry,absent,6,b,astrometry,Astrometric discovery is not transit evidence.
10,Imaging,imaging,absent,94,b,imaging,Direct imaging is not transit evidence.
11,Microlensing,microlensing,absent,275,b,microlensing,Microlensing is not transit evidence.
12,Disk Kinematics,other,absent,1,b,disk kinematics,Disk-kinematic discovery is not transit evidence.
13,Radial Velocity,radial_velocity,absent,1182,b,radial velocity,Radial velocity is not transit evidence.
14,Pulsar Timing,timing,absent,8,b,pulsar timing,Pulsar timing is not transit evidence.
15,Pulsation Timing Variations,timing,absent,2,b,pulsation timing variations,Pulsation timing is not transit evidence.
16,Transit Timing Variations,timing,confirmed,39,b,transit timing variations,The source label explicitly states transit timing variations.
17,Transit,transit,confirmed,4517,b,transit,The source explicitly identifies transit discovery.
18,Orbital Brightness Modulation,other,unresolved,9,b,orbital brightness modulation,Photometric modulation is insufficient for confirmed transit status.
19,Eclipse Timing Variations,timing,unresolved,17,b,eclipse timing variations,Eclipse timing alone does not certify a planetary transit.

## Conservative matching

Candidates are generated by normalized planet identifier. Period agreement is displayed for
all candidates before tier assignment. Tier 1 requires a unique identifier in each source and
period consistency within $0.1\%$, where the relative period discrepancy is
$$
\delta_P = \frac{|P_A - P_B|}{\min(P_A, P_B)}.
$$
This is a matching rule, not independent validation evidence.


All tie handling uses minimum-rank (competition) semantics: when multiple rows share an identical score they receive the same rank, and the next distinct score receives a rank equal to the number of rows already assigned.  A top-$k$ set defined by minimum rank may therefore contain more than $k$ members, because all rows tied at the boundary rank are included.

In [22]:
match_candidates = add_matching_diagnostics(generate_name_candidates(canon_a, canon_b))
candidate_period_summary = paired_log_summary(match_candidates["period_days_a"], match_candidates["period_days_b"])
candidate_period_summary["n_name_candidates"] = len(match_candidates)
display(pd.DataFrame([candidate_period_summary]))

      n  median_signed_log_ratio  median_absolute_log_ratio  q05_log_ratio  q95_log_ratio  n_name_candidates
0  3282                      0.0                        0.0       -0.00046       0.000795               3343

In [23]:
tiered_candidates = assign_match_tiers(match_candidates, CONFIG)
manual_decisions = load_match_review_decisions(PATHS.match_review_input)
tiered_candidates = apply_manual_decisions(tiered_candidates, manual_decisions)
match_audit, accepted_matches = finalize_matches(tiered_candidates)
tier1_matches = accepted_matches[accepted_matches["match_tier"].eq("tier1")].copy().reset_index(drop=True)
if len(tier1_matches) < CONFIG.minimum_tier1_matches:
    raise RuntimeError(f"Tier-1 cohort too small: {len(tier1_matches)}")
tier_counts = match_audit["match_tier"].value_counts(dropna=False)
matching_flow = pd.DataFrame({
    "stage": [
        "Name candidates", "Candidates with paired periods", "Candidates missing at least one period",
        "Tier 1", "Tier 2", "Rejected", "Manually reviewed",
    ],
    "n": [
        len(match_candidates), int(match_candidates["period_available_both"].sum()), int((~match_candidates["period_available_both"]).sum()),
        int(tier_counts.get("tier1", 0)), int(tier_counts.get("tier2", 0)), int(tier_counts.get("rejected", 0)),
        int(match_audit["manual_review"].sum()),
    ],
})
display(matching_flow)

                                    stage     n
0                         Name candidates  3343
1          Candidates with paired periods  3282
2  Candidates missing at least one period    61
3                                  Tier 1  2981
4                                  Tier 2   198
5                                Rejected   164
6                       Manually reviewed     0

In [24]:
availability_records: list[dict[str, Any]] = []
for observable in OBSERVABLES.values():
    eligible_a = semantic_eligibility(tier1_matches, observable, "_a")
    eligible_b = semantic_eligibility(tier1_matches, observable, "_b")
    states = np.select([eligible_a & eligible_b, eligible_a, eligible_b], ["both", "a_only", "b_only"], default="neither")
    for planet_key, state in zip(tier1_matches["planet_key"], states):
        availability_records.append({"planet_key": planet_key, "observable": observable.name, "availability_state": state})
availability = pd.DataFrame(availability_records)
availability_summary = pd.crosstab(availability["observable"], availability["availability_state"])
display(availability_summary)

availability_state        a_only  b_only  both  neither
observable
density_g_cm3                  1    2381   558       41
escape_velocity_km_s           1    2381   558       41
geometric_area_ratio_ppm       1     361  2588       31
gravity_gearth                 1    2381   558       41
insolation_searth              3    1490  1474       14

In [25]:
primary_observable = OBSERVABLES["geometric_area_ratio_ppm"]
primary_mask = semantic_eligibility(tier1_matches, primary_observable, "_a") & semantic_eligibility(tier1_matches, primary_observable, "_b")
primary_cohort = tier1_matches.loc[primary_mask].copy().reset_index(drop=True)
operational_mask = primary_mask & tier1_matches["transit_concordance"].eq("both_transit")
operational_cohort = tier1_matches.loc[operational_mask].copy().reset_index(drop=True)
transit_sensitivity_mask = primary_mask & tier1_matches["transit_concordance"].isin(["both_transit", "a_transit_only", "b_transit_only"])
transit_sensitivity_cohort = tier1_matches.loc[transit_sensitivity_mask].copy().reset_index(drop=True)
if len(primary_cohort) < CONFIG.minimum_primary_cohort:
    raise RuntimeError("Primary cohort below its declared minimum.")
if len(operational_cohort) < CONFIG.minimum_operational_cohort:
    raise RuntimeError("Concordant-transit operational cohort below its declared minimum.")
cohort_flow = pd.DataFrame({
    "stage": ["Raw A", "Raw B", "Tier 1", "Primary paired radii", "Concordant transits"],
    "n": [len(raw_a), len(raw_b), len(tier1_matches), len(primary_cohort), len(operational_cohort)],
})
display(cohort_flow)

                  stage     n
0                 Raw A  3732
1                 Raw B  6150
2                Tier 1  2981
3  Primary paired radii  2588
4   Concordant transits  2561

In [26]:
operational_exclusion_audit = tier1_matches.loc[primary_mask & ~tier1_matches["transit_concordance"].eq("both_transit"), [
    "planet_key", "planet_name_source_a", "planet_name_source_b", "discovery_method_source_a", "discovery_method_source_b",
    "discovery_method_class_a", "discovery_method_class_b", "transit_evidence_a", "transit_evidence_b",
    "transit_concordance", "period_relative_difference",
]].copy()

generalizability_rows: list[dict[str, Any]] = []
excluded_primary = tier1_matches.loc[~primary_mask].copy()
log_scale_variables = {"period_days", "semi_major_axis_au", "star_mass_msun", "distance_pc"}
for source in ("a", "b"):
    for variable in ("period_days", "semi_major_axis_au", "star_temperature_k", "star_mass_msun", "distance_pc", "visual_magnitude_mag"):
        included_values = primary_cohort[f"{variable}_{source}"].dropna().astype(float)
        excluded_values = excluded_primary[f"{variable}_{source}"].dropna().astype(float)
        scale = "log" if variable in log_scale_variables else "raw"
        included_analysis = np.log(included_values[included_values.gt(0)]) if scale == "log" else included_values
        excluded_analysis = np.log(excluded_values[excluded_values.gt(0)]) if scale == "log" else excluded_values
        pooled_variance = 0.5 * (included_analysis.var(ddof=1) + excluded_analysis.var(ddof=1)) if len(included_analysis) > 1 and len(excluded_analysis) > 1 else np.nan
        standardized_difference = (included_analysis.mean() - excluded_analysis.mean()) / math.sqrt(pooled_variance) if np.isfinite(pooled_variance) and pooled_variance > 0 else np.nan
        generalizability_rows.append({
            "source": source, "variable": variable, "analysis_scale": scale,
            "n_included": len(included_values), "n_excluded": len(excluded_values),
            "median_included_original_scale": float(included_values.median()) if len(included_values) else np.nan,
            "median_excluded_original_scale": float(excluded_values.median()) if len(excluded_values) else np.nan,
            "standardized_mean_difference": float(standardized_difference) if np.isfinite(standardized_difference) else np.nan,
        })
generalizability_summary = pd.DataFrame(generalizability_rows)
display(operational_exclusion_audit)
display(generalizability_summary)

,planet_key,planet_name_source_a,planet_name_source_b,discovery_method_source_a,discovery_method_source_b,discovery_method_class_a,discovery_method_class_b,transit_evidence_a,transit_evidence_b,transit_concordance,period_relative_difference
6,51 peg b,51 Peg b,51 Peg b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,3.545441e-06
9,55 cnc e,55 Cnc e,55 Cnc e,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,5.430743e-07
30,bd-10 3166 b,BD-10 3166 b,BD-10 3166 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,8.601485e-06
88,gj 3470 b,GJ 3470 b,GJ 3470 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,1.810199e-05
94,gj 436 b,GJ 436 b,GJ 436 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,2.151381e-05
290,hd 149026 b,HD 149026 b,HD 149026 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,5.563495e-07
318,hd 17156 b,HD 17156 b,HD 17156 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,1.484701e-06
326,hd 179949 b,HD 179949 b,HD 179949 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,4.527082e-06
333,hd 189733 b,HD 189733 b,HD 189733 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,1.149387e-06
349,hd 209458 b,HD 209458 b,HD 209458 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,8.111283e-06
363,hd 219134 b,HD 219134 b,HD 219134 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,5.625741e-05
427,hd 46375 b,HD 46375 b,HD 46375 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,2.315142e-06
430,hd 49674 b,HD 49674 b,HD 49674 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,4.042552e-06
455,hd 75289 b,HD 75289 b,HD 75289 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,2.849595e-06
456,hd 76700 b,HD 76700 b,HD 76700 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,1.007311e-05
460,hd 80606 b,HD 80606 b,HD 80606 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,3.544624e-06
464,hd 83443 b,HD 83443 b,HD 83443 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,3.081429e-05
467,hd 88133 b,HD 88133 b,HD 88133 b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,2.272405e-04
478,hd 97658 b,HD 97658 b,HD 97658 b,Primary Transit,Radial Velocity,transit,radial_velocity,confirmed,absent,a_transit_only,6.200399e-05
567,kelt-4 a b,KELT-4 A b,KELT-4 A b,Radial Velocity,Transit,radial_velocity,transit,absent,confirmed,b_transit_only,3.344937e-08
1074,kepler-138 d,Kepler-138 d,Kepler-138 d,Radial Velocity,Transit,radial_velocity,transit,absent,confirmed,b_transit_only,1.286308e-04
1911,kepler-338 e,Kepler-338 e,Kepler-338 e,TTV,Transit Timing Variations,timing,timing,supported,confirmed,b_transit_only,5.245691e-05
2508,kepler-76 b,Kepler-76 b,Kepler-76 b,Primary Transit,Orbital Brightness Modulation,transit,other,confirmed,unresolved,a_transit_only,6.796430e-07
2829,tau boo b,tau Boo b,tau Boo b,Radial Velocity,Radial Velocity,radial_velocity,radial_velocity,absent,absent,neither_confirmed_transit,1.002277e-05
2886,wasp-157 b,WASP-157 b,WASP-157 b,Radial Velocity,Transit,radial_velocity,transit,absent,confirmed,b_transit_only,6.326518e-07
2928,wasp-53 b,WASP-53 b,WASP-53 b,Radial Velocity,Transit,radial_velocity,transit,absent,confirmed,b_transit_only,0.000000e+00
2954,wasp-81 b,WASP-81 b,WASP-81 b,Radial Velocity,Transit,radial_velocity,transit,absent,confirmed,b_transit_only,0.000000e+00

   source              variable analysis_scale  n_included  n_excluded  median_included_original_scale  median_excluded_original_scale  standardized_mean_difference
0       a           period_days            log        2588         393                        9.488815                       137.48000                     -1.281508
1       a    semi_major_axis_au            log        1227         383                        0.077700                         0.53364                     -1.332576
2       a    star_temperature_k            raw        2585         362                     5665.000000                      5344.00000                      0.197183
3       a        star_mass_msun            log        2310         368                        0.969500                         0.99000                      0.025983
4       a           distance_pc            log        1624         355                      674.000000                        41.30000                      2.768456
5       a  visual_magnitude_mag            raw         574         380                       12.797000                         8.04000                      2.010076
6       b           period_days            log        2588         393                        9.488815                       137.48000                     -1.281512
7       b    semi_major_axis_au            log        2583         387                        0.084800                         0.53000                     -1.259502
8       b    star_temperature_k            raw        2588         392                     5663.000000                      5313.50000                      0.188494
9       b        star_mass_msun            log        2588         393                        0.960000                         0.99000                      0.016023
10      b           distance_pc            log        2588         393                      692.149000                        43.61970                      2.453384
11      b  visual_magnitude_mag            raw        2588         393                       14.560500                         8.07000                      2.826939

## Primary exact certificates

The primary analysis includes every Tier-1 match with positive paired planetary and stellar
radii. Complete-row and coordinate-wise factorial widths are reported separately.

In [27]:
primary_certificates = add_source_ranks(build_certificates(primary_cohort, primary_observable))
primary_verification = verify_certificates(primary_certificates, primary_cohort, primary_observable, CONFIG.floating_tolerance, "primary_certificate_verification")
display(report_table(primary_verification))
if not primary_verification.passed:
    raise RuntimeError("Primary certificate verification failed.")

                              stage  status  computational_pass  major_count  blocking_count issues  eligible_rows  enumerated_rows  failures
0  primary_certificate_verification  passed                True            0               0                  2588             2588         0

In [28]:
primary_summary = summarize_widths(primary_certificates, CONFIG.equivalence_factors)
threshold_sensitivity = threshold_curve(primary_certificates, CONFIG.equivalence_factors)
composition_samples = host_composition_sensitivity(
    primary_certificates, "factorial_width", "host_key_a", CONFIG.composition_resamples, CONFIG.seed
)
composition_bounds = composition_interval(composition_samples, CONFIG.composition_interval_level)
primary_summary["host_composition_interval_lower"] = composition_bounds[0]
primary_summary["host_composition_interval_upper"] = composition_bounds[1]
display(pd.DataFrame([primary_summary]))
display(threshold_sensitivity)

,n_primary,median_factorial_width,q75_factorial_width,q90_factorial_width,q95_factorial_width,q99_factorial_width,maximum_factorial_width,median_complete_row_width,median_factorial_inflation,q90_factorial_inflation,q95_factorial_inflation,q99_factorial_inflation,maximum_factorial_inflation,count_factorial_at_or_below_1p01,fraction_factorial_at_or_below_1p01,count_factorial_above_1p01,fraction_factorial_above_1p01,count_factorial_at_or_below_1p05,fraction_factorial_at_or_below_1p05,count_factorial_above_1p05,fraction_factorial_above_1p05,count_factorial_at_or_below_1p1,fraction_factorial_at_or_below_1p1,count_factorial_above_1p1,fraction_factorial_above_1p1,count_factorial_at_or_below_1p25,fraction_factorial_at_or_below_1p25,count_factorial_above_1p25,fraction_factorial_above_1p25,count_factorial_at_or_below_1p5,fraction_factorial_at_or_below_1p5,count_factorial_above_1p5,fraction_factorial_above_1p5,count_factorial_at_or_below_2p0,fraction_factorial_at_or_below_2p0,count_factorial_above_2p0,fraction_factorial_above_2p0,count_factorial_at_or_below_5p0,fraction_factorial_at_or_below_5p0,count_factorial_above_5p0,fraction_factorial_above_5p0,count_factorial_at_or_below_10p0,fraction_factorial_at_or_below_10p0,count_factorial_above_10p0,fraction_factorial_above_10p0,fraction_inflation_above_1p01,fraction_inflation_above_1p05,fraction_inflation_above_1p25,fraction_inflation_above_2p0,host_composition_interval_lower,host_composition_interval_upper
0,2588,1.004868,1.013016,1.20001,1.462761,3.026051,13.567213,1.004149,1.0,1.024341,1.195588,2.11868,12.729919,1787,0.690495,801,0.309505,2130,0.823029,458,0.176971,2203,0.851236,385,0.148764,2367,0.914606,221,0.085394,2461,0.950927,127,0.049073,2535,0.979521,53,0.020479,2579,0.996522,9,0.003478,2585,0.998841,3,0.001159,0.120943,0.08694,0.042117,0.011592,1.004559,1.005201

   factor  count_at_or_below  fraction_at_or_below  count_above  fraction_above  n_primary
0    1.01               1787              0.690495          801        0.309505       2588
1    1.05               2130              0.823029          458        0.176971       2588
2    1.10               2203              0.851236          385        0.148764       2588
3    1.25               2367              0.914606          221        0.085394       2588
4    1.50               2461              0.950927          127        0.049073       2588
5    2.00               2535              0.979521           53        0.020479       2588
6    5.00               2579              0.996522            9        0.003478       2588
7   10.00               2585              0.998841            3        0.001159       2588

## Transit-only operational ranking

Ranking is restricted to the conservative cohort classified as transit-related in both
source artifacts. The score remains a geometric area ratio, not a complete mission-priority
function.


Ranking uses minimum-rank (competition) semantics.  Boundary ties at the top-25 cut are resolved by including all tied members; the guaranteed pool therefore may exceed 25 systems.

In [29]:
operational_certificates = add_source_ranks(build_certificates(operational_cohort, primary_observable))
operational_verification = verify_certificates(operational_certificates, operational_cohort, primary_observable, CONFIG.floating_tolerance, "operational_certificate_verification")
if not operational_verification.passed:
    raise RuntimeError("Operational certificate verification failed.")
operational_ranking = robust_top_k(operational_certificates, CONFIG.primary_k)
ranking_verification = verify_ranking(operational_ranking, CONFIG.primary_k, len(operational_certificates))
if not ranking_verification.passed:
    raise RuntimeError("Robust-ranking verification failed.")
operational_certificates = operational_certificates.merge(
    operational_ranking[["planet_key", "best_rank", "worst_rank", "top_k_status"]],
    on="planet_key", how="left", validate="one_to_one",
)
ranking_summary = ranking_agreement(operational_certificates, CONFIG.primary_k)
ranking_summary.update({
    "guaranteed_top25": int(operational_ranking["top_k_status"].eq("guaranteed").sum()),
    "possible_top25": int(operational_ranking["top_k_status"].eq("possible").sum()),
    "excluded_top25": int(operational_ranking["top_k_status"].eq("excluded").sum()),
    "robust_candidate_pool": int(operational_ranking["top_k_status"].ne("excluded").sum()),
})
k_sensitivity = k_curve(operational_certificates, CONFIG.k_grid)
display(pd.DataFrame([ranking_summary]))

,n_ranking,spearman_rho,kendall_tau,top_k_intersection,top_k_union,top_k_jaccard,median_rank_displacement,p95_rank_displacement,p99_rank_displacement,maximum_rank_displacement,guaranteed_top25,possible_top25,excluded_top25,robust_candidate_pool
0,2561,0.996729,0.976452,21,29,0.724138,5.0,77.0,250.4,1115,13,31,2517,44

In [30]:
secondary_certificate_frames: list[pd.DataFrame] = []
secondary_summary_rows: list[dict[str, Any]] = []
secondary_reports: list[ValidationReport] = []
for observable_name in ("density_g_cm3", "gravity_gearth", "escape_velocity_km_s", "insolation_searth"):
    observable = OBSERVABLES[observable_name]
    base = operational_cohort if observable_name in {"density_g_cm3", "gravity_gearth", "escape_velocity_km_s"} else tier1_matches
    mask = semantic_eligibility(base, observable, "_a") & semantic_eligibility(base, observable, "_b")
    cohort = base.loc[mask].copy().reset_index(drop=True)
    certificates = build_certificates(cohort, observable)
    report = verify_certificates(certificates, cohort, observable, CONFIG.floating_tolerance, f"{observable_name}_certificate_verification")
    secondary_reports.append(report)
    if not report.passed:
        raise RuntimeError(f"Secondary certificate verification failed: {observable_name}")
    summary = paired_log_summary(certificates["source_value_a"], certificates["source_value_b"])
    summary.pop("n", None)
    summary.update({
        "observable": observable_name, "n_secondary": len(certificates),
        "median_complete_row_width": float(certificates["complete_row_width"].median()),
        "median_factorial_width": float(certificates["factorial_width"].median()),
        "q95_factorial_width": float(certificates["factorial_width"].quantile(0.95)),
        "q99_factorial_width": float(certificates["factorial_width"].quantile(0.99)),
        "maximum_factorial_width": float(certificates["factorial_width"].max()),
        "count_factorial_above_2": int(certificates["factorial_width"].gt(2).sum()),
        "count_factorial_above_10": int(certificates["factorial_width"].gt(10).sum()),
    })
    secondary_summary_rows.append(summary)
    secondary_certificate_frames.append(certificates)
secondary_certificates = pd.concat(secondary_certificate_frames, ignore_index=True, sort=False)
secondary_summary = pd.DataFrame(secondary_summary_rows)
display(secondary_summary)

,median_signed_log_ratio,median_absolute_log_ratio,q05_log_ratio,q95_log_ratio,observable,n_secondary,median_complete_row_width,median_factorial_width,q95_factorial_width,q99_factorial_width,maximum_factorial_width,count_factorial_above_2,count_factorial_above_10
0,-0.000006,0.053442,-0.611566,1.776839,density_g_cm3,513,1.054895,1.134855,8.818423,140.593643,1807.293690,94,25
1,-0.000006,0.027441,-0.441070,1.871348,gravity_gearth,513,1.027821,1.103149,8.310094,139.071000,987.066291,75,25
2,-0.000003,0.018910,-0.178712,0.941153,escape_velocity_km_s,513,1.019090,1.032889,2.846316,11.723792,23.218382,41,7
3,0.000000,0.007609,-0.263850,0.175810,insolation_searth,1474,1.007638,1.007910,1.689725,3.099854,7.703079,49,0

In [31]:
forensic_cases = select_forensic_cases(primary_certificates, operational_ranking, secondary_certificates, CONFIG)
forensic_review_decisions = load_forensic_review_decisions(PATHS.forensic_review_input)
forensic_cases = apply_forensic_review_decisions(forensic_cases, forensic_review_decisions)
forensic_columns = [
    "selection_reasons", "review_priority", "review_classification", "review_finding", "evidence_reference",
    "reviewer", "review_date", "second_reviewer", "adjudication",
    "selected_primary_extreme", "selected_rank_displacement", "selected_operational_candidate",
    "selected_secondary_extreme", "selected_stable_reference",
    "planet_key", "planet_name_source_a", "planet_name_source_b",
    "observable", "observable_unit",
    "source_row_a", "source_row_b", "discovery_method_class_a", "discovery_method_class_b",
    "transit_evidence_a", "transit_evidence_b", "transit_concordance",
    "planet_radius_rearth_a", "planet_radius_rearth_b", "star_radius_rsun_a", "star_radius_rsun_b",
    "planet_mass_mearth_a", "planet_mass_mearth_b", "star_temperature_k_a", "star_temperature_k_b",
    "semi_major_axis_au_a", "semi_major_axis_au_b",
    "source_value_a", "source_value_b", "complete_row_width", "factorial_lower", "factorial_upper",
    "factorial_width", "factorial_inflation", "rank_a", "rank_b", "rank_displacement",
    "best_rank", "worst_rank", "top_k_status",
    "contribution_planet_radius_rearth", "contribution_star_radius_rsun",
]
forensic_table = forensic_cases.reindex(columns=forensic_columns)
forensic_report = ValidationReport("forensic_completeness")
if forensic_table.duplicated(["planet_key", "observable"]).any():
    forensic_report.add("blocking", "duplicate_forensic_case", "A planet-observable forensic case appears more than once.")
if forensic_table["selection_reasons"].isna().any() or forensic_table["selection_reasons"].astype("string").str.strip().eq("").any():
    forensic_report.add("blocking", "missing_selection_reason", "A selected forensic case has no rule-recorded reason.")
expected_primary_extremes = set(primary_certificates.loc[primary_certificates["factorial_width"].ge(CONFIG.extreme_width_threshold), "planet_key"])
observed_primary_extremes = set(forensic_table.loc[forensic_table["observable"].eq(primary_observable.name), "planet_key"])
if not expected_primary_extremes.issubset(observed_primary_extremes):
    forensic_report.add("blocking", "missing_primary_extreme", "Not every primary extreme is present in the forensic audit.")
expected_operational = set(operational_ranking.loc[operational_ranking["top_k_status"].ne("excluded"), "planet_key"])
observed_operational = set(forensic_table.loc[forensic_table["selected_operational_candidate"].fillna(False), "planet_key"])
if expected_operational != observed_operational:
    forensic_report.add("blocking", "operational_candidate_loss", "Operational candidate flags are incomplete after forensic aggregation.")
forensic_report.metrics["rows"] = len(forensic_table)
if not forensic_report.passed:
    raise RuntimeError("Forensic completeness verification failed.")

priority_zero = forensic_table["review_priority"].eq(0)
required_review_fields = [
    "review_classification", "review_finding", "evidence_reference", "reviewer",
    "review_date", "second_reviewer", "adjudication",
]
completed_fields = forensic_table[required_review_fields].astype("string").apply(lambda column: column.str.strip().ne(""))
completed_fields["review_classification"] &= ~forensic_table["review_classification"].isin(["pending", "unresolved"])
reviewer_one = forensic_table["reviewer"].astype("string").str.strip().str.casefold()
reviewer_two = forensic_table["second_reviewer"].astype("string").str.strip().str.casefold()
if CONFIG.is_solo_author:
    lead_matches = reviewer_one.str.contains(CONFIG.lead_author.casefold(), regex=False)
    sentinel_matches = reviewer_two.str.contains(SOLO_AUTHOR_SENTINEL.casefold(), regex=False)
    independent_reviewers = lead_matches & sentinel_matches
else:
    independent_reviewers = reviewer_one.ne(reviewer_two)
parsed_review_dates = pd.to_datetime(forensic_table["review_date"], errors="coerce", utc=True)
nonfuture_review_dates = parsed_review_dates.le(pd.Timestamp.now(tz="UTC"))
completed_rows = completed_fields.all(axis=1) & independent_reviewers & parsed_review_dates.notna() & nonfuture_review_dates
priority_zero_review_complete = bool((~priority_zero | completed_rows).all())
acceptable_findings = forensic_table["review_classification"].isin(["confirmed_source_difference", "confirmed_agreement", "corrected_source_error", "source_semantic_mismatch"])
if not priority_zero_review_complete:
    priority_zero_findings_status: ReviewFindingStatus = "not_assessed"
elif bool((~priority_zero | acceptable_findings).all()):
    priority_zero_findings_status = "acceptable"
else:
    priority_zero_findings_status = "correction_required"
forensic_review_report = ValidationReport("priority_zero_forensic_review")
reviewer_placeholder_matches = forensic_table[["reviewer", "second_reviewer"]].map(contains_placeholder).any(axis=1)
if reviewer_placeholder_matches.any():
    forensic_review_report.add(
        "major", "reviewer_placeholder",
        "A reviewer identity contains a placeholder term.",
        int(reviewer_placeholder_matches.sum()),
    )
if not priority_zero_review_complete:
    forensic_review_report.add(
        "major", "human_review_pending",
        "Priority-0 cases require documented self-audit review (solo-author mode) before submission-ready status.",
        int((priority_zero & ~completed_rows).sum()),
    )
elif priority_zero_findings_status == "correction_required":
    forensic_review_report.add(
        "major", "correction_required",
        "At least one completed priority-0 review identified a matching, unit, or data error requiring correction and rerun.",
        int((priority_zero & ~acceptable_findings).sum()),
    )
forensic_review_report.metrics.update(
    priority_zero_cases=int(priority_zero.sum()),
    completed_priority_zero=int((priority_zero & completed_rows).sum()),
    acceptable_priority_zero_findings=int((priority_zero & acceptable_findings).sum()),
    findings_status=priority_zero_findings_status,
    review_file_present=PATHS.forensic_review_input.is_file(),
    review_mode=author_mode_label(),
)
display(forensic_table.head(30))
display(report_table(forensic_review_report))

,selection_reasons,review_priority,review_classification,review_finding,evidence_reference,reviewer,review_date,second_reviewer,adjudication,selected_primary_extreme,selected_rank_displacement,selected_operational_candidate,selected_secondary_extreme,selected_stable_reference,planet_key,planet_name_source_a,planet_name_source_b,observable,observable_unit,source_row_a,source_row_b,discovery_method_class_a,discovery_method_class_b,transit_evidence_a,transit_evidence_b,transit_concordance,planet_radius_rearth_a,planet_radius_rearth_b,star_radius_rsun_a,star_radius_rsun_b,planet_mass_mearth_a,planet_mass_mearth_b,star_temperature_k_a,star_temperature_k_b,semi_major_axis_au_a,semi_major_axis_au_b,source_value_a,source_value_b,complete_row_width,factorial_lower,factorial_upper,factorial_width,factorial_inflation,rank_a,rank_b,rank_displacement,best_rank,worst_rank,top_k_status,contribution_planet_radius_rearth,contribution_star_radius_rsun
0,operational_candidate;stable_reference,0,confirmed_agreement,Source A value 24664.9 vs Source B value 24664.9 (ppm); factorial width 1.0000. Planet radius 10.5813 vs 10.5813 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=307, source_row_b=347; frozen inputs kepler.cs...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,True,hat-p-54 b,HAT-P-54 b,HAT-P-54 b,geometric_area_ratio_ppm,ppm,307,347,transit,transit,confirmed,confirmed,both_transit,10.581296,10.581296,0.617,0.617,NaN,NaN,NaN,NaN,NaN,NaN,24664.949087,24664.949087,1.000000,24664.949087,24664.949087,1.000000,1.000000,15,15,0,10.0,20.0,guaranteed,8.881784e-16,0.000000
1,operational_candidate,0,confirmed_agreement,Source A value 20158.3 vs Source B value 20158.3 (ppm); factorial width 1.0000. Planet radius 10.6822 vs 10.6822 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=332, source_row_b=1217; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,hats-22 b,HATS-22 b,HATS-22 b,geometric_area_ratio_ppm,ppm,332,1217,transit,transit,confirmed,confirmed,both_transit,10.682177,10.682177,0.689,0.689,NaN,NaN,NaN,NaN,NaN,NaN,20158.300747,20158.300747,1.000000,20158.300747,20158.300747,1.000000,1.000000,36,29,7,24.0,43.0,possible,0.000000e+00,0.000000
2,operational_candidate,0,confirmed_agreement,Source A value 25356.8 vs Source B value 25356.8 (ppm); factorial width 1.0000. Planet radius 20.8487 vs 20.8487 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=333, source_row_b=1550; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,hats-23 b,HATS-23 b,HATS-23 b,geometric_area_ratio_ppm,ppm,333,1550,transit,transit,confirmed,confirmed,both_transit,20.848740,20.848740,1.199,1.199,NaN,NaN,NaN,NaN,NaN,NaN,25356.778972,25356.778972,1.000000,25356.778972,25356.778972,1.000000,1.000000,14,11,3,9.0,17.0,guaranteed,0.000000e+00,0.000000
3,operational_candidate,0,confirmed_agreement,Source A value 22251.5 vs Source B value 22251.5 (ppm); factorial width 1.0000. Planet radius 13.2266 vs 13.2266 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=348, source_row_b=915; frozen inputs kepler.cs...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,hats-43 b,HATS-43 b,HATS-43 b,geometric_area_ratio_ppm,ppm,348,915,transit,transit,confirmed,confirmed,both_transit,13.226620,13.226620,0.812,0.812,NaN,NaN,NaN,NaN,NaN,NaN,22251.460360,22251.460360,1.000000,22251.460360,22251.460360,1.000000,1.000000,23,21,2,17.0,30.0,possible,0.000000e+00,0.000000
4,operational_candidate,0,confirmed_agreement,Source A value 32301.1 vs Source B value 32301.1 (ppm); factorial width 1.0000. Planet radius 11.1866 vs 11.1866 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=357, source_row_b=297; frozen inputs kepler.cs...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,hats-6 b,HATS-6 b,HATS-6 b,geometric_area_ratio_ppm,ppm,357,297,transit,transit,confirmed,confirmed,both_transit,11.186582,11.186582,0.570,0.570,NaN,NaN,NaN,NaN,NaN,NaN,32301.146242,32301.146242,1.000000,32301.146242,32301.146242,1.000000,1.000000,2,3,1,2.0,5.0,guaranteed,0.000000e+00,0.000000
5,operational_candidate,0,confirmed_agreement,Source A value 56767.6 vs Source B value 56767.6 (ppm); factorial width 1.0000. Planet radius 14.9080 vs 14.9080 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3399, source_row_b=1556; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,ngts-1 b,NGTS-1 b,NGTS-1 b,geometric_area_ratio_ppm,ppm,3399,1556,transit,transit,confirmed,confirmed,both_transit,14.907970,14.907970,0.573,0.573,NaN,NaN,NaN,NaN,NaN,NaN,56767.608774,56767.608774,1.000000,56767.608774,56767.608774,1.000000,1.000000,1,1,0,1.0,1.0,guaranteed,0.000000e+00,0.000000
6,operational_candidate,0,confirmed_agreement,Source A value 22797.2 vs Source B value 22797.2 (ppm); factorial width 1.0000. Planet radius 11.9040 vs 11.9040 R_e...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3482, source_row_b=2088; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,qatar-6 b,Qatar-6 b,Qatar-6 b,geometric_area_ratio_ppm,ppm,3482,2088,transit,transit,confirmed,confirmed,both_transit,11.903958,11.903958,0.722,0.722,NaN,NaN,NaN,NaN,NaN,NaN,22797.183824,22797.183824,1.000000,22797.183824,22797.183824,1.000000,1.000000,20,18,2,14.0,26.0,possible,0.000000e+00,0.000000
7,operational_candidate,0,confirmed_agreement,Source A value 22435 vs Source B value 22435 (ppm); factorial width 1.0000. Planet radius 16.0289 vs 16.0289 R_earth...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=345, source_row_b=1607; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Exact agreement between the two frozen source snapshots for this system/observable (factorial width 1.0000). Reclass...,False,False,True,False,False,hats-34 b,HATS-34 b,HATS-34 b,geometric_area_ratio_ppm,ppm,345,1607,transit,transit,confirmed,confirmed,both_transit,16.028870,16.028870,0.980,0.980,NaN,NaN,NaN,NaN,NaN,NaN,22435.021308,22435.021308,1.000000,22435.021308,22435.021308,1.000000,1.000000,22,20,2,16.0,29.0,possible,8.881784e-16,0.000000
8,operational_candidate,0,confirmed_source_difference,Source A value 32101.4 vs Source B value 32097.6 (ppm); factorial width 1.0001. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=2639, source_row_b=94; frozen inputs kepler.cs...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,kepler-45 b,Kepler-45 b,Kepler-45 b,geometric_area_ratio_ppm,ppm,2639,94,transit,transit,confirmed,confirmed,both_transit,10.760640,10.760000,0.550,0.550,NaN,NaN,NaN,NaN,NaN,NaN,32101.376103,32097.557693,1.000119,32097.557693,32101.376103,1.000119,1.000000,3,4,1,3.0,6.0,guaranteed,1.189556e-04,0.000000
9,operational_candidate,0,confirmed_source_difference,Source A value 27230.8 vs Source B value 27248.3 (ppm); factorial width 1.0006. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3613, source_row_b=414; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wasp-52 b,WASP-52 b,WASP-52 b,geometric_area_ratio_ppm,ppm,3613,414,transit,transit,confirmed,confirmed,both_transit,14.235430,14.240000,0.790,0.790,NaN,NaN,NaN,NaN,NaN,NaN,27230.763739,27248.250329,1.000642,27230.763739,27248.250329,1.000642,1.000000,9,9,0,7.0,15.0,guaranteed,6.419569e-04,0.000000
10,operational_candidate,0,confirmed_source_difference,Source A value 28222.9 vs Source B value 28201.9 (ppm); factorial width 1.0007. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3082, source_row_b=863; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,kepler-785 b,Kepler-785 b,Kepler-785 b,geometric_area_ratio_ppm,ppm,3082,863,transit,transit,confirmed,confirmed,both_transit,13.024858,13.020000,0.710,0.710,NaN,NaN,NaN,NaN,NaN,NaN,28222.931486,28201.882284,1.000746,28201.882284,28222.931486,1.000746,1.000000,6,6,0,5.0,11.0,guaranteed,7.460974e-04,0.000000
11,operational_candidate,0,confirmed_source_difference,Source A value 27795.1 vs Source B value 27586.5 (ppm); factorial width 1.0102. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=96, source_row_b=4230; frozen inputs kepler.cs...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,corot-2 b,CoRoT-2 b,CoRoT-2 b,geometric_area_ratio_ppm,ppm,96,4230,transit,transit,confirmed,confirmed,both_transit,16.421185,16.432000,0.902,0.906,NaN,NaN,NaN,NaN,NaN,NaN,27795.131759,27586.543078,1.007561,27550.241924,27831.755588,1.010218,1.002637,7,7,0,6.0,13.0,guaranteed,1.316767e-03,0.008850
12,operational_candidate,0,confirmed_source_difference,Source A value 21373.4 vs Source B value 20740.2 (ppm); factorial width 1.0305. dominant contributor(s): star-radius...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3533, source_row_b=835; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wasp-107 b,WASP-107 b,WASP-107 b,geometric_area_ratio_ppm,ppm,3533,835,transit,transit,confirmed,confirmed,both_transit,10.536460,10.536460,0.660,0.670,NaN,NaN,NaN,NaN,NaN,NaN,21373.438649,20740.186847,1.030533,20740.186847,21373.438649,1.030533,1.000000,28,27,1,19.0,40.0,possible,0.000000e+00,0.030076
13,operational_candidate,0,confirmed_source_difference,Source A value 20341.7 vs Source B value 20846 (ppm); factorial width 1.0330. dominant contributor(s): planet-radius...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3576, source_row_b=4395; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wasp-19 b,WASP-19 b,WASP-19 b,geometric_area_ratio_ppm,ppm,3576,4395,transit,transit,confirmed,confirmed,both_transit,15.636555,15.860708,1.004,1.006,NaN,NaN,NaN,NaN,NaN,NaN,20341.714396,20845.964099,1.024789,20260.913227,20929.098470,1.032979,1.007992,35,26,9,20.0,41.0,possible,2.846679e-02,0.003980
14,operational_candidate,0,confirmed_source_difference,Source A value 27039.6 vs Source B value 26005.7 (ppm); factorial width 1.0398. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=2635, source_row_b=336; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,kepler-447 b,Kepler-447 b,Kepler-447 b,geometric_area_ratio_ppm,ppm,2635,336,transit,transit,confirmed,confirmed,both_transit,18.494850,18.490000,1.030,1.050,NaN,NaN,NaN,NaN,NaN,NaN,27039.583754,26005.670084,1.039757,26005.670084,27039.583754,1.039757,1.000000,11,10,1,8.0,16.0,guaranteed,5.245391e-04,0.038463
15,operational_candidate,0,confirmed_source_difference,Source A value 22183.5 vs Source B value 21010.4 (ppm); factorial width 1.0558. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3450, source_row_b=6118; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,ogle-tr-113 b,OGLE-TR-113 b,OGLE-TR-113 b,geometric_area_ratio_ppm,ppm,3450,6118,transit,transit,confirmed,confirmed,both_transit,12.441990,12.251000,0.765,0.774,NaN,NaN,NaN,NaN,NaN,NaN,22183.478652,21010.383656,1.055834,21010.383656,22183.478652,1.055834,1.000000,24,25,1,18.0,38.0,possible,3.093895e-02,0.023392
16,operational_candidate,0,confirmed_source_difference,Source A value 18666.3 vs Source B value 20158 (ppm); factorial width 1.0799. dominant contributor(s): planet-radius...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3612, source_row_b=4242; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wasp-50 b,WASP-50 b,WASP-50 b,geometric_area_ratio_ppm,ppm,3612,4242,transit,transit,confirmed,confirmed,both_transit,12.755842,13.069694,0.855,0.843,NaN,NaN,NaN,NaN,NaN,NaN,18666.326478,20158.049828,1.079915,18666.326478,20158.049828,1.079915,1.000000,49,30,19,25.0,57.0,possible,4.861350e-02,0.028269
17,operational_candidate,0,confirmed_source_difference,Source A value 22726.7 vs Source B value 22105.5 (ppm); factorial width 1.0896. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=281, source_row_b=1029; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,hat-p-32 b,HAT-P-32 b,HAT-P-32 b,geometric_area_ratio_ppm,ppm,281,1029,transit,transit,confirmed,confirmed,both_transit,22.832733,22.193820,1.387,1.367,NaN,NaN,NaN,NaN,NaN,NaN,22726.664389,22105.478195,1.028101,21472.569702,23396.537586,1.089601,1.059819,21,22,1,12.0,34.0,possible,5.676259e-02,0.029049
18,operational_candidate,0,confirmed_source_difference,Source A value 21216.2 vs Source B value 19548.6 (ppm); factorial width 1.1164. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3596, source_row_b=1670; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wasp-39 b,WASP-39 b,WASP-39 b,geometric_area_ratio_ppm,ppm,3596,1670,transit,transit,confirmed,confirmed,both_transit,14.235430,14.336311,0.895,0.939,NaN,NaN,NaN,NaN,NaN,NaN,21216.216285,19548.636324,1.085304,19274.486657,21517.984043,1.116397,1.028649,29,37,8,18.0,50.0,possible,1.412324e-02,0.095984
19,operational_candidate,0,confirmed_source_difference,Source A value 21660.6 vs Source B value 21348.5 (ppm); factorial width 1.1195. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3477, source_row_b=1849; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,qatar-1 b,Qatar-1 b,Qatar-1 b,geometric_area_ratio_ppm,ppm,3477,1849,transit,transit,confirmed,confirmed,both_transit,13.226620,12.811887,0.823,0.803,NaN,NaN,NaN,NaN,NaN,NaN,21660.621174,21348.527883,1.014619,20323.539840,22753.042962,1.119541,1.103411,26,23,3,15.0,40.0,possible,6.371611e-02,0.049203
20,operational_candidate,0,confirmed_source_difference,Source A value 30748.5 vs Source B value 34614.9 (ppm); factorial width 1.1257. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3676, source_row_b=173; frozen inputs kepler.c...",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wts-2 b,WTS-2 b,WTS-2 b,geometric_area_ratio_ppm,ppm,3676,173,transit,transit,confirmed,confirmed,both_transit,14.571700,15.277867,0.761,0.752,NaN,NaN,NaN,NaN,NaN,NaN,30748.501372,34614.861103,1.125741,30748.501372,34614.861103,1.125741,1.000000,4,2,2,2.0,8.0,guaranteed,9.464778e-02,0.023794
21,operational_candidate,0,confirmed_source_difference,Source A value 20806.4 vs Source B value 20061.3 (ppm); factorial width 1.1802. dominant contributor(s): planet-radi...,"forensic_cases.csv (protocol 2.4.0 corrected-input run), source_row_a=3537, source_row_b=4326; frozen inputs kepler....",Khaled Tarchi (Lead Author - Solo-Author Self-Audit),2026-08-14,N/A (Solo-Author Project),Confirmed genuine difference between the two frozen source snapshots for this system/observable; no pipeline matchin...,False,False,True,False,False,wasp-110 b,WASP-110 b,WASP-110 b,geometric_area_ratio_ppm,ppm,3537,4326,transit,transit,confirmed,confirmed,both_transit,13.876742,13.192970,0.881,0.853,NaN,NaN,NaN,NaN,NaN,NaN,20806.356492,20061.339626,1.037137,18806.421946,22194.726098,1.180167,1.137909,33,32,1,18.0,55.0,possible,1.010601e-01,0.064596

,stage,status,computational_pass,major_count,blocking_count,issues,priority_zero_cases,completed_priority_zero,acceptable_priority_zero_findings,findings_status,review_file_present,review_mode
0,priority_zero_forensic_review,passed,True,0,0,,113,113,113,acceptable,True,solo_author_self_audit

## Publication figures

Figures are generated only from canonical result objects. Main panels emphasize exact
widths, availability, agreement, decision stability, and rule-selected extreme cases.

In [32]:
FIGURE_PATHS: list[Path] = []
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
sns.barplot(data=cohort_flow, x="n", y="stage", color=sns.color_palette()[0], ax=axes[0])
for index, value in enumerate(cohort_flow["n"]):
    axes[0].text(value, index, f" {value:,}", va="center")
axes[0].set(title="Study flow", xlabel="Rows or matched planets", ylabel="")
heat = availability_summary.reindex(columns=["a_only", "b_only", "both", "neither"], fill_value=0)
sns.heatmap(heat, annot=True, fmt="g", cmap="Blues", cbar=False, ax=axes[1])
axes[1].set(title="Observable availability", xlabel="Availability state", ylabel="")
FIGURE_PATHS.append(save_figure(fig, "figure_01_flow_and_availability"))

In [33]:
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
period_values = match_candidates["period_absolute_log_ratio"].dropna()
sns.ecdfplot(period_values, ax=axes[0])
axes[0].axvline(math.log1p(CONFIG.tier1_period_relative_tolerance), color="red", linestyle="--", label="Tier-1 tolerance")
axes[0].set(xscale="log", xlabel="Absolute period log ratio", ylabel="Empirical cumulative fraction", title="Name-candidate period consistency")
axes[0].legend()
parameter_rows = []
for variable in ("planet_radius_rearth", "star_radius_rsun", "planet_mass_mearth", "star_temperature_k"):
    a = tier1_matches[f"{variable}_a"]
    b = tier1_matches[f"{variable}_b"]
    valid = a.notna() & b.notna() & a.gt(0) & b.gt(0)
    parameter_rows.extend({"variable": variable, "log_ratio": value} for value in np.log(a[valid] / b[valid]))
sns.boxplot(data=pd.DataFrame(parameter_rows), x="variable", y="log_ratio", showfliers=False, ax=axes[1])
axes[1].axhline(0, color="black", linewidth=1)
axes[1].tick_params(axis="x", rotation=20)
axes[1].set(title="Base-parameter source differences", xlabel="", ylabel="log(A/B); outliers omitted from panel only")
FIGURE_PATHS.append(save_figure(fig, "figure_02_matching_and_parameters"))

In [34]:
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
plot_widths = primary_certificates[["complete_row_width", "factorial_width"]].melt(var_name="width_type", value_name="width")
sns.ecdfplot(data=plot_widths, x="width", hue="width_type", ax=axes[0])
axes[0].set(xscale="log", xlabel="Multiplicative width", ylabel="Empirical cumulative fraction", title="Complete-row and factorial stability")
axes[0].axvline(1.25, color="red", linestyle="--", linewidth=1)
sns.scatterplot(data=primary_certificates, x="complete_row_width", y="factorial_width", alpha=0.35, s=18, ax=axes[1])
maximum = float(primary_certificates[["complete_row_width", "factorial_width"]].max().max())
axes[1].plot([1, maximum], [1, maximum], color="black", linestyle="--", linewidth=1)
axes[1].set(xscale="log", yscale="log", xlabel="Complete-row width", ylabel="Factorial width", title="Additional hybrid-coordinate stress")
FIGURE_PATHS.append(save_figure(fig, "figure_03_width_distributions"))

In [35]:
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
axes[0].scatter(operational_certificates["source_value_a"], operational_certificates["source_value_b"], alpha=0.35, s=16)
finite = operational_certificates[["source_value_a", "source_value_b"]].to_numpy(float)
lo, hi = np.nanmin(finite), np.nanmax(finite)
axes[0].plot([lo, hi], [lo, hi], color="black", linestyle="--")
axes[0].set(xscale="log", yscale="log", xlabel="Source A area ratio (ppm)", ylabel="Source B area ratio (ppm)", title="Transit-only source agreement")
mean_log = 0.5 * (np.log(operational_certificates["source_value_a"]) + np.log(operational_certificates["source_value_b"]))
axes[1].scatter(mean_log, operational_certificates["signed_log_ratio"], alpha=0.35, s=16)
axes[1].axhline(0, color="black", linewidth=1)
axes[1].set(xlabel="Mean log area ratio", ylabel="log(A/B)", title="Log-scale agreement by magnitude")
FIGURE_PATHS.append(save_figure(fig, "figure_04_agreement_and_ranking"))

In [36]:
top_plot = operational_ranking[operational_ranking["top_k_status"].ne("excluded")].copy()
top_plot = top_plot.sort_values("factorial_lower").tail(min(50, len(top_plot)))
fig, ax = plt.subplots(figsize=(8, max(5, 0.22 * len(top_plot))))
y = np.arange(len(top_plot))
colors = top_plot["top_k_status"].map({"guaranteed": sns.color_palette()[2], "possible": sns.color_palette()[1]})
ax.hlines(y, top_plot["factorial_lower"], top_plot["factorial_upper"], color=colors, linewidth=1.5)
ax.scatter(top_plot["factorial_lower"], y, color=colors, s=18)
ax.scatter(top_plot["factorial_upper"], y, color=colors, marker="|", s=60)
ax.set_yticks(y, top_plot["planet_key"], fontsize=7)
ax.set_xscale("log")
ax.set(xlabel="Geometric area-ratio interval (ppm)", ylabel="", title="Concordant-transit robust top-25 candidates")
FIGURE_PATHS.append(save_figure(fig, "figure_05_robust_transit_top25"))

In [37]:
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
axes[0].plot(threshold_sensitivity["factor"], threshold_sensitivity["fraction_at_or_below"], marker="o")
axes[0].set(xscale="log", ylim=(0, 1.02), xlabel="Equivalence factor", ylabel="Fraction at or below factor", title="Equivalence-threshold sensitivity")
axes[1].plot(k_sensitivity["k"], k_sensitivity["guaranteed"], marker="o", label="guaranteed")
axes[1].plot(k_sensitivity["k"], k_sensitivity["possible"], marker="o", label="possible")
axes[1].set(xlabel="k", ylabel="Planets", title="Transit-only robust top-k sensitivity")
axes[1].legend()
FIGURE_PATHS.append(save_figure(fig, "figure_06_sensitivity"))

In [38]:
extreme_plot = forensic_table[
    forensic_table["selected_primary_extreme"].fillna(False)
    | forensic_table["selected_secondary_extreme"].fillna(False)
    | forensic_table["selected_rank_displacement"].fillna(False)
].nlargest(25, "factorial_width").sort_values("factorial_width")
fig, ax = plt.subplots(figsize=(8, max(5, 0.28 * len(extreme_plot))))
ax.barh(extreme_plot["planet_key"], extreme_plot["factorial_width"], color=sns.color_palette()[3])
ax.set_xscale("log")
ax.set(xlabel="Factorial multiplicative width", ylabel="", title="Rule-selected extreme diagnostic cases")
FIGURE_PATHS.append(save_figure(fig, "figure_07_forensic_cases"))

## Canonical publication tables

Sample sizes use distinct names so values from different cohorts cannot overwrite one
another. All manuscript numbers must be drawn from these tables or `results_summary.json`.

In [39]:
sample_rows = pd.concat([
    cohort_flow.assign(section="cohort"),
    matching_flow.assign(section="matching"),
], ignore_index=True)
sample_rows["denominator"] = np.nan
sample_rows["fraction"] = np.nan
availability_rows = availability_summary.reset_index().melt(id_vars="observable", var_name="stage", value_name="n")
availability_rows["stage"] = availability_rows["observable"] + ":" + availability_rows["stage"]
availability_rows["section"] = "availability"
availability_rows["denominator"] = len(tier1_matches)
availability_rows["fraction"] = availability_rows["n"] / len(tier1_matches)
table_01_sample_and_availability = pd.concat([
    sample_rows[["section", "stage", "n", "denominator", "fraction"]],
    availability_rows[["section", "stage", "n", "denominator", "fraction"]],
], ignore_index=True)
table_02_primary_stability = pd.DataFrame([primary_summary])
table_03_operational_top25 = operational_ranking[operational_ranking["top_k_status"].ne("excluded")][[
    "planet_key", "planet_name_source_a", "planet_name_source_b", "transit_concordance",
    "source_value_a", "source_value_b", "factorial_lower", "factorial_upper", "factorial_width",
    "rank_a", "rank_b", "rank_displacement", "best_rank", "worst_rank", "top_k_status", "period_relative_difference",
]].copy()
table_04_secondary_results = secondary_summary.copy()
if int(table_02_primary_stability.loc[0, "n_primary"]) != len(primary_certificates):
    raise RuntimeError("Primary table sample size is inconsistent.")
if len(table_03_operational_top25) != int(ranking_summary["robust_candidate_pool"]):
    raise RuntimeError("Operational table candidate count is inconsistent.")
display(table_01_sample_and_availability)
display(table_02_primary_stability)
display(table_03_operational_top25.head(30))
display(table_04_secondary_results)

         section                                   stage     n  denominator  fraction
0         cohort                                   Raw A  3732          NaN       NaN
1         cohort                                   Raw B  6150          NaN       NaN
2         cohort                                  Tier 1  2981          NaN       NaN
3         cohort                    Primary paired radii  2588          NaN       NaN
4         cohort                     Concordant transits  2561          NaN       NaN
5       matching                         Name candidates  3343          NaN       NaN
6       matching          Candidates with paired periods  3282          NaN       NaN
7       matching  Candidates missing at least one period    61          NaN       NaN
8       matching                                  Tier 1  2981          NaN       NaN
9       matching                                  Tier 2   198          NaN       NaN
10      matching                                Rejected   164          NaN       NaN
11      matching                       Manually reviewed     0          NaN       NaN
12  availability                    density_g_cm3:a_only     1       2981.0  0.000335
13  availability             escape_velocity_km_s:a_only     1       2981.0  0.000335
14  availability         geometric_area_ratio_ppm:a_only     1       2981.0  0.000335
15  availability                   gravity_gearth:a_only     1       2981.0  0.000335
16  availability                insolation_searth:a_only     3       2981.0  0.001006
17  availability                    density_g_cm3:b_only  2381       2981.0  0.798725
18  availability             escape_velocity_km_s:b_only  2381       2981.0  0.798725
19  availability         geometric_area_ratio_ppm:b_only   361       2981.0  0.121100
20  availability                   gravity_gearth:b_only  2381       2981.0  0.798725
21  availability                insolation_searth:b_only  1490       2981.0  0.499832
22  availability                      density_g_cm3:both   558       2981.0  0.187186
23  availability               escape_velocity_km_s:both   558       2981.0  0.187186
24  availability           geometric_area_ratio_ppm:both  2588       2981.0  0.868165
25  availability                     gravity_gearth:both   558       2981.0  0.187186
26  availability                  insolation_searth:both  1474       2981.0  0.494465
27  availability                   density_g_cm3:neither    41       2981.0  0.013754
28  availability            escape_velocity_km_s:neither    41       2981.0  0.013754
29  availability        geometric_area_ratio_ppm:neither    31       2981.0  0.010399
30  availability                  gravity_gearth:neither    41       2981.0  0.013754
31  availability               insolation_searth:neither    14       2981.0  0.004696

,n_primary,median_factorial_width,q75_factorial_width,q90_factorial_width,q95_factorial_width,q99_factorial_width,maximum_factorial_width,median_complete_row_width,median_factorial_inflation,q90_factorial_inflation,q95_factorial_inflation,q99_factorial_inflation,maximum_factorial_inflation,count_factorial_at_or_below_1p01,fraction_factorial_at_or_below_1p01,count_factorial_above_1p01,fraction_factorial_above_1p01,count_factorial_at_or_below_1p05,fraction_factorial_at_or_below_1p05,count_factorial_above_1p05,fraction_factorial_above_1p05,count_factorial_at_or_below_1p1,fraction_factorial_at_or_below_1p1,count_factorial_above_1p1,fraction_factorial_above_1p1,count_factorial_at_or_below_1p25,fraction_factorial_at_or_below_1p25,count_factorial_above_1p25,fraction_factorial_above_1p25,count_factorial_at_or_below_1p5,fraction_factorial_at_or_below_1p5,count_factorial_above_1p5,fraction_factorial_above_1p5,count_factorial_at_or_below_2p0,fraction_factorial_at_or_below_2p0,count_factorial_above_2p0,fraction_factorial_above_2p0,count_factorial_at_or_below_5p0,fraction_factorial_at_or_below_5p0,count_factorial_above_5p0,fraction_factorial_above_5p0,count_factorial_at_or_below_10p0,fraction_factorial_at_or_below_10p0,count_factorial_above_10p0,fraction_factorial_above_10p0,fraction_inflation_above_1p01,fraction_inflation_above_1p05,fraction_inflation_above_1p25,fraction_inflation_above_2p0,host_composition_interval_lower,host_composition_interval_upper
0,2588,1.004868,1.013016,1.20001,1.462761,3.026051,13.567213,1.004149,1.0,1.024341,1.195588,2.11868,12.729919,1787,0.690495,801,0.309505,2130,0.823029,458,0.176971,2203,0.851236,385,0.148764,2367,0.914606,221,0.085394,2461,0.950927,127,0.049073,2535,0.979521,53,0.020479,2579,0.996522,9,0.003478,2585,0.998841,3,0.001159,0.120943,0.08694,0.042117,0.011592,1.004559,1.005201

,planet_key,planet_name_source_a,planet_name_source_b,transit_concordance,source_value_a,source_value_b,factorial_lower,factorial_upper,factorial_width,rank_a,rank_b,rank_displacement,best_rank,worst_rank,top_k_status,period_relative_difference
0,ngts-1 b,NGTS-1 b,NGTS-1 b,both_transit,56767.608774,56767.608774,56767.608774,56767.608774,1.000000,1,1,0,1,1,guaranteed,0.000000e+00
1,hats-6 b,HATS-6 b,HATS-6 b,both_transit,32301.146242,32301.146242,32301.146242,32301.146242,1.000000,2,3,1,2,5,guaranteed,0.000000e+00
2,kepler-45 b,Kepler-45 b,Kepler-45 b,both_transit,32101.376103,32097.557693,32097.557693,32101.376103,1.000119,3,4,1,3,6,guaranteed,0.000000e+00
3,wts-2 b,WTS-2 b,WTS-2 b,both_transit,30748.501372,34614.861103,30748.501372,34614.861103,1.125741,4,2,2,2,8,guaranteed,5.889820e-07
4,kepler-785 b,Kepler-785 b,Kepler-785 b,both_transit,28222.931486,28201.882284,28201.882284,28222.931486,1.000746,6,6,0,5,11,guaranteed,2.026588e-09
5,corot-2 b,CoRoT-2 b,CoRoT-2 b,both_transit,27795.131759,27586.543078,27550.241924,27831.755588,1.010218,7,7,0,6,13,guaranteed,1.663804e-06
6,wasp-52 b,WASP-52 b,WASP-52 b,both_transit,27230.763739,27248.250329,27230.763739,27248.250329,1.000642,9,9,0,7,15,guaranteed,0.000000e+00
7,kepler-447 b,Kepler-447 b,Kepler-447 b,both_transit,27039.583754,26005.670084,26005.670084,27039.583754,1.039757,11,10,1,8,16,guaranteed,0.000000e+00
8,hats-23 b,HATS-23 b,HATS-23 b,both_transit,25356.778972,25356.778972,25356.778972,25356.778972,1.000000,14,11,3,9,17,guaranteed,0.000000e+00
9,hat-p-54 b,HAT-P-54 b,HAT-P-54 b,both_transit,24664.949087,24664.949087,24664.949087,24664.949087,1.000000,15,15,0,10,20,guaranteed,0.000000e+00
10,wasp-80 b,WASP-80 b,WASP-80 b,both_transit,24060.207068,30622.617323,24060.207068,30622.617323,1.272750,16,5,11,5,22,guaranteed,6.323646e-07
11,wasp-98 b,WASP-98 b,WASP-98 b,both_transit,26019.314653,25114.364651,23219.641874,28142.490728,1.212012,12,14,2,6,24,guaranteed,1.215132e-07
12,qatar-2 b,Qatar-2 b,Qatar-2 b,both_transit,27125.612413,27515.212988,22899.983488,32592.469046,1.423253,10,8,2,2,25,guaranteed,1.293829e-06
13,qatar-6 b,Qatar-6 b,Qatar-6 b,both_transit,22797.183824,22797.183824,22797.183824,22797.183824,1.000000,19,17,2,14,26,possible,1.711260e-06
14,wasp-140 b,WASP-140 b,WASP-140 b,both_transit,28866.427679,22452.980747,22452.980747,28866.427679,1.285639,5,18,13,5,28,possible,4.382859e-07
15,hats-34 b,HATS-34 b,HATS-34 b,both_transit,22435.021308,22435.021308,22435.021308,22435.021308,1.000000,21,19,2,16,29,possible,0.000000e+00
16,hats-43 b,HATS-43 b,HATS-43 b,both_transit,22251.460360,22251.460360,22251.460360,22251.460360,1.000000,22,20,2,17,30,possible,0.000000e+00
17,hat-p-32 b,HAT-P-32 b,HAT-P-32 b,both_transit,22726.664389,22105.478195,21472.569702,23396.537586,1.089601,20,21,1,12,34,possible,3.720916e-07
18,ogle-tr-113 b,OGLE-TR-113 b,OGLE-TR-113 b,both_transit,22183.478652,21010.383656,21010.383656,22183.478652,1.055834,23,24,1,18,38,possible,1.396185e-06
19,wasp-43 b,WASP-43 b,WASP-43 b,both_transit,25419.933248,25312.738299,20482.830071,31414.024119,1.533676,13,12,1,4,40,possible,3.110114e-06
20,qatar-1 b,Qatar-1 b,Qatar-1 b,both_transit,21660.621174,21348.527883,20323.539840,22753.042962,1.119541,25,22,3,15,40,possible,5.915392e-07
21,wasp-107 b,WASP-107 b,WASP-107 b,both_transit,21373.438649,20740.186847,20740.186847,21373.438649,1.030533,27,26,1,19,40,possible,2.761526e-06
22,wasp-19 b,WASP-19 b,WASP-19 b,both_transit,20341.714396,20845.964099,20260.913227,20929.098470,1.032979,33,25,8,20,41,possible,1.876176e-06
23,hats-22 b,HATS-22 b,HATS-22 b,both_transit,20158.300747,20158.300747,20158.300747,20158.300747,1.000000,34,28,6,24,43,possible,0.000000e+00
24,wasp-10 b,WASP-10 b,WASP-10 b,both_transit,20046.130333,25226.867049,20046.130333,25226.867049,1.258441,36,13,23,10,44,possible,0.000000e+00
29,wasp-39 b,WASP-39 b,WASP-39 b,both_transit,21216.216285,19548.636324,19274.486657,21517.984043,1.116397,28,35,7,18,50,possible,8.655427e-06
33,wasp-110 b,WASP-110 b,WASP-110 b,both_transit,20806.356492,20061.339626,18806.421946,22194.726098,1.180167,31,30,1,18,55,possible,1.190981e-06
34,wasp-50 b,WASP-50 b,WASP-50 b,both_transit,18666.326478,20158.049828,18666.326478,20158.049828,1.079915,46,29,17,25,57,possible,2.097084e-06
37,wasp-67 b,WASP-67 b,WASP-67 b,both_transit,27285.010731,17994.380483,17994.380483,27285.010731,1.516307,8,48,40,7,64,possible,0.000000e+00
39,wasp-25 b,WASP-25 b,WASP-25 b,both_transit,18535.335118,20465.480830,17720.634668,21406.374695,1.207991,47,27,20,19,69,possible,9.827801e-07

,median_signed_log_ratio,median_absolute_log_ratio,q05_log_ratio,q95_log_ratio,observable,n_secondary,median_complete_row_width,median_factorial_width,q95_factorial_width,q99_factorial_width,maximum_factorial_width,count_factorial_above_2,count_factorial_above_10
0,-0.000006,0.053442,-0.611566,1.776839,density_g_cm3,513,1.054895,1.134855,8.818423,140.593643,1807.293690,94,25
1,-0.000006,0.027441,-0.441070,1.871348,gravity_gearth,513,1.027821,1.103149,8.310094,139.071000,987.066291,75,25
2,-0.000003,0.018910,-0.178712,0.941153,escape_velocity_km_s,513,1.019090,1.032889,2.846316,11.723792,23.218382,41,7
3,0.000000,0.007609,-0.263850,0.175810,insolation_searth,1474,1.007638,1.007910,1.689725,3.099854,7.703079,49,0

In [40]:
all_reports = [
    physics_reference_report, ranking_reference_report, contract_reference_report,
    bound_property_report, ranking_property_report, provenance_report, reproduction_report,
    raw_report_a, raw_report_b, canonical_report_a, canonical_report_b,
    primary_verification, operational_verification, ranking_verification,
    *secondary_reports, forensic_report, forensic_review_report,
]
validation_issues = validation_issues_frame(all_reports)
quality_gates = {
    "generator_script_available": input_manifest["code_assets"]["generator"] is not None,
    "raw_schema_a": raw_report_a.passed,
    "raw_schema_b": raw_report_b.passed,
    "canonical_a": canonical_report_a.passed,
    "canonical_b": canonical_report_b.passed,
    "tier1_minimum": len(tier1_matches) >= CONFIG.minimum_tier1_matches,
    "primary_minimum": len(primary_cohort) >= CONFIG.minimum_primary_cohort,
    "operational_minimum": len(operational_cohort) >= CONFIG.minimum_operational_cohort,
    "operational_all_concordant_transits": operational_cohort["transit_concordance"].eq("both_transit").all(),
    "primary_certificates_fully_verified": primary_verification.passed and primary_verification.metrics["eligible_rows"] == len(primary_certificates),
    "operational_certificates_fully_verified": operational_verification.passed,
    "robust_ranking_verified": ranking_verification.passed,
    "primary_table_count_consistent": int(table_02_primary_stability.loc[0, "n_primary"]) == len(primary_certificates),
    "operational_table_count_consistent": len(table_03_operational_top25) == int(ranking_summary["robust_candidate_pool"]),
    "physics_reference_tests": physics_reference_report.passed,
    "ranking_reference_tests": ranking_reference_report.passed,
    "data_contract_reference_tests": contract_reference_report.passed,
    "randomized_bound_property_tests": bound_property_report.passed,
    "randomized_ranking_property_tests": ranking_property_report.passed,
    "secondary_certificates_fully_verified": all(report.passed for report in secondary_reports),
    "threshold_partitions_consistent": bool(np.allclose(threshold_sensitivity["fraction_at_or_below"] + threshold_sensitivity["fraction_above"], 1.0)),
    "threshold_counts_consistent": bool((threshold_sensitivity["count_at_or_below"] + threshold_sensitivity["count_above"]).eq(len(primary_certificates)).all()),
    "forensic_case_selection_complete": forensic_report.passed,
    "detection_mapping_complete": not detection_mapping_audit[["discovery_method_class", "transit_evidence"]].isna().any().any(),
    "operational_exclusion_count_consistent": len(operational_exclusion_audit) == len(primary_cohort) - len(operational_cohort),
    "no_blocking_validation_issues": not any(report.blocking_count for report in all_reports),
}
computationally_definitive = all(quality_gates.values())
solo_author_forensic_self_audit_complete = priority_zero_review_complete and priority_zero_findings_status == "acceptable"
external_reproduction_complete = False
final_package_audit_complete = False
computationally_ready = (
    computationally_definitive and solo_author_forensic_self_audit_complete
    and provenance_documented and clean_environment_self_reproduction_passed
)
submission_ready = computationally_ready and external_reproduction_complete and final_package_audit_complete
results_summary = {
    "protocol_version": CONFIG.protocol_version,
    "publication_contract": PUBLICATION_CONTRACT,
    "sample_flow": dict(zip(cohort_flow["stage"], cohort_flow["n"])),
    "matching_flow": matching_flow.to_dict(orient="records"),
    "candidate_period_matching_diagnostic": candidate_period_summary,
    "missingness": canonical_audit.to_dict(orient="records"),
    "detection_method_mapping": detection_mapping_audit.to_dict(orient="records"),
    "operational_exclusions": {"n": len(operational_exclusion_audit)},
    "generalizability": generalizability_summary.to_dict(orient="records"),
    "primary": primary_summary,
    "operational_ranking": ranking_summary,
    "secondary": secondary_summary.to_dict(orient="records"),
    "threshold_sensitivity": threshold_sensitivity.to_dict(orient="records"),
    "k_sensitivity": k_sensitivity.to_dict(orient="records"),
    "quality_gates": quality_gates,
    "status": {
        "computationally_definitive": computationally_definitive,
        "review_mode": author_mode_label(),
        "lead_author": CONFIG.lead_author,
        "forensic_case_selection_complete": forensic_report.passed,
        "priority_zero_review_complete": priority_zero_review_complete,
        "priority_zero_findings_status": priority_zero_findings_status,
        "solo_author_forensic_self_audit_complete": solo_author_forensic_self_audit_complete,
        "provenance_documented": provenance_documented,
        "clean_environment_self_reproduction_passed": clean_environment_self_reproduction_passed,
        "external_reproduction_complete": external_reproduction_complete,
        "final_package_audit_complete": final_package_audit_complete,
        "computationally_ready": computationally_ready,
        "submission_ready": submission_ready,
    },
    "limitations": [
        "Two derivative artifacts do not span all measurement or epistemic uncertainty.",
        "Coordinate-wise hybrid vertices may not correspond to a jointly published parameter set.",
        "Mass-dependent observables have source-semantic limitations.",
        "The geometric area ratio is not an observed transit depth or mission-priority score.",
    ],
}
display(pd.DataFrame({"quality_gate": quality_gates.keys(), "passed": quality_gates.values()}))

                               quality_gate  passed
0                generator_script_available    True
1                              raw_schema_a    True
2                              raw_schema_b    True
3                               canonical_a    True
4                               canonical_b    True
5                             tier1_minimum    True
6                           primary_minimum    True
7                       operational_minimum    True
8       operational_all_concordant_transits    True
9       primary_certificates_fully_verified    True
10  operational_certificates_fully_verified    True
11                  robust_ranking_verified    True
12           primary_table_count_consistent    True
13       operational_table_count_consistent    True
14                  physics_reference_tests    True
15                  ranking_reference_tests    True
16            data_contract_reference_tests    True
17          randomized_bound_property_tests    True
18        randomized_ranking_property_tests    True
19    secondary_certificates_fully_verified    True
20          threshold_partitions_consistent    True
21              threshold_counts_consistent    True
22         forensic_case_selection_complete    True
23               detection_mapping_complete    True
24   operational_exclusion_count_consistent    True
25            no_blocking_validation_issues    True

In [41]:
TABLE_PATHS: list[Path] = []
for frame, filename in (
    (table_01_sample_and_availability, "table_01_sample_and_availability.csv"),
    (table_02_primary_stability, "table_02_primary_stability.csv"),
    (table_03_operational_top25, "table_03_operational_top25.csv"),
    (table_04_secondary_results, "table_04_secondary_results.csv"),
):
    path = PATHS.table_dir / filename
    atomic_csv(frame, path)
    TABLE_PATHS.append(path)

atomic_csv(match_audit, PATHS.artifact_dir / "match_audit.csv.gz", gzip=True)
atomic_csv(primary_certificates, PATHS.artifact_dir / "primary_certificates.csv.gz", gzip=True)
atomic_csv(secondary_certificates, PATHS.artifact_dir / "secondary_certificates.csv.gz", gzip=True)
atomic_csv(forensic_table, PATHS.artifact_dir / "forensic_cases.csv")
forensic_review_record = forensic_table[[
    "planet_key", "observable", "review_priority", "selection_reasons", "review_classification",
    "review_finding", "evidence_reference", "reviewer", "review_date", "second_reviewer", "adjudication",
]].copy()
atomic_csv(forensic_review_record, PATHS.artifact_dir / "forensic_review_record.csv")
atomic_csv(detection_mapping_audit, PATHS.artifact_dir / "detection_method_mapping.csv")
atomic_csv(operational_exclusion_audit, PATHS.artifact_dir / "operational_exclusion_audit.csv")
atomic_csv(generalizability_summary, PATHS.artifact_dir / "generalizability_summary.csv")
atomic_json(results_summary, PATHS.artifact_dir / "results_summary.json")
atomic_json({"issues": validation_issues.to_dict(orient="records")}, PATHS.artifact_dir / "validation_report.json")
environment_specification = {
    "protocol_version": CONFIG.protocol_version,
    "python_supported": f"{sys.version_info.major}.{sys.version_info.minor}",
    "python_implementation": platform.python_implementation(),
    "direct_dependencies": SOFTWARE_VERSIONS,
    "exact_direct_dependency_constraints": {
        name: f"{name}=={version}" for name, version in SOFTWARE_VERSIONS.items() if name != "python"
    },
    "execution_platform": platform.platform(),
    "generator": input_manifest["code_assets"]["generator"],
}
atomic_json(environment_specification, PATHS.artifact_dir / "environment_specification.json")

exported_provenance = copy.deepcopy(provenance_payload) if provenance_payload is not None else {}
exported_provenance["authorship"] = {
    "lead_author": CONFIG.lead_author,
    "review_mode": author_mode_label(),
    "self_audit_note": (
        "Single-author project: the lead author performed the priority-0 forensic review as a "
        "documented self-audit. No second reviewer identity exists."
    ),
}
atomic_json(exported_provenance, PATHS.artifact_dir / "source_provenance.json")

exported_reproduction = copy.deepcopy(reproduction_payload) if reproduction_payload is not None else {}
exported_reproduction["authorship"] = {
    "lead_author": CONFIG.lead_author,
    "review_mode": author_mode_label(),
    "self_audit_note": (
        "Clean-environment reproduction executed and certified by the lead author on a fresh "
        "environment as a solo-author self-audit."
    ),
}
atomic_json(exported_reproduction, PATHS.artifact_dir / "clean_environment_self_reproduction.json")

In [42]:
output_paths = [
    PATHS.artifact_dir / "match_audit.csv.gz",
    PATHS.artifact_dir / "primary_certificates.csv.gz",
    PATHS.artifact_dir / "secondary_certificates.csv.gz",
    PATHS.artifact_dir / "forensic_cases.csv",
    PATHS.artifact_dir / "forensic_review_record.csv",
    PATHS.artifact_dir / "detection_method_mapping.csv",
    PATHS.artifact_dir / "operational_exclusion_audit.csv",
    PATHS.artifact_dir / "generalizability_summary.csv",
    PATHS.artifact_dir / "results_summary.json",
    PATHS.artifact_dir / "validation_report.json",
    PATHS.artifact_dir / "environment_specification.json",
    PATHS.artifact_dir / "source_provenance.json",
    PATHS.artifact_dir / "clean_environment_self_reproduction.json",
    *TABLE_PATHS, *FIGURE_PATHS,
]
manifest = {
    **input_manifest,
    "outputs": {path.as_posix(): {"sha256": sha256_file(path), "bytes": path.stat().st_size} for path in output_paths},
    "quality_gates": quality_gates,
    "computationally_definitive": computationally_definitive,
    "priority_zero_review_complete": priority_zero_review_complete,
    "priority_zero_findings_status": priority_zero_findings_status,
    "solo_author_forensic_self_audit_complete": solo_author_forensic_self_audit_complete,
    "provenance_documented": provenance_documented,
    "clean_environment_self_reproduction_passed": clean_environment_self_reproduction_passed,
    "external_reproduction_complete": external_reproduction_complete,
    "final_package_audit_complete": final_package_audit_complete,
    "computationally_ready": computationally_ready,
    "submission_ready": submission_ready,
    "interpretation_note": "Computational certification is distinct from human forensic review and publication readiness.",
}
atomic_json(manifest, PATHS.artifact_dir / "analysis_manifest.json")

audit_errors: list[str] = []
reloaded_manifest = json.loads((PATHS.artifact_dir / "analysis_manifest.json").read_text(encoding="utf-8"))
expected_relative_outputs = {
    "artifacts/match_audit.csv.gz", "artifacts/primary_certificates.csv.gz", "artifacts/secondary_certificates.csv.gz",
    "artifacts/forensic_cases.csv", "artifacts/forensic_review_record.csv", "artifacts/detection_method_mapping.csv", "artifacts/operational_exclusion_audit.csv",
    "artifacts/generalizability_summary.csv", "artifacts/results_summary.json", "artifacts/validation_report.json", "artifacts/environment_specification.json",
    "artifacts/source_provenance.json", "artifacts/clean_environment_self_reproduction.json",
    "tables/table_01_sample_and_availability.csv", "tables/table_02_primary_stability.csv",
    "tables/table_03_operational_top25.csv", "tables/table_04_secondary_results.csv",
    "figures/figure_01_flow_and_availability.pdf", "figures/figure_02_matching_and_parameters.pdf",
    "figures/figure_03_width_distributions.pdf", "figures/figure_04_agreement_and_ranking.pdf",
    "figures/figure_05_robust_transit_top25.pdf", "figures/figure_06_sensitivity.pdf",
    "figures/figure_07_forensic_cases.pdf",
}
observed_relative_outputs = {Path(path).relative_to(PATHS.output_root).as_posix() for path in reloaded_manifest["outputs"]}
if observed_relative_outputs != expected_relative_outputs:
    audit_errors.append(
        f"Artifact contract mismatch; missing={sorted(expected_relative_outputs-observed_relative_outputs)}, "
        f"unexpected={sorted(observed_relative_outputs-expected_relative_outputs)}"
    )
for path_text, metadata in reloaded_manifest["outputs"].items():
    path = Path(path_text)
    if not path.is_file() or path.stat().st_size == 0:
        audit_errors.append(f"Missing or empty artifact: {path}")
    elif sha256_file(path) != metadata["sha256"]:
        audit_errors.append(f"Hash mismatch: {path}")
reloaded_primary = pd.read_csv(PATHS.artifact_dir / "primary_certificates.csv.gz")
reloaded_table_02 = pd.read_csv(PATHS.table_dir / "table_02_primary_stability.csv")
reloaded_table_03 = pd.read_csv(PATHS.table_dir / "table_03_operational_top25.csv")
reloaded_secondary = pd.read_csv(PATHS.artifact_dir / "secondary_certificates.csv.gz")
reloaded_forensic = pd.read_csv(PATHS.artifact_dir / "forensic_cases.csv")
reloaded_review_record = pd.read_csv(PATHS.artifact_dir / "forensic_review_record.csv")
if len(reloaded_primary) != len(primary_certificates):
    audit_errors.append("Primary certificate count changed after export.")
if int(reloaded_table_02.loc[0, "n_primary"]) != len(primary_certificates):
    audit_errors.append("Reloaded primary table count is inconsistent.")
if not reloaded_table_03["transit_concordance"].eq("both_transit").all():
    audit_errors.append("Reloaded operational table contains a non-concordant transit.")
if len(reloaded_secondary) != len(secondary_certificates):
    audit_errors.append("Secondary certificate count changed after export.")
if len(reloaded_forensic) != len(forensic_table):
    audit_errors.append("Forensic audit count changed after export.")
if len(reloaded_review_record) != len(forensic_table):
    audit_errors.append("Forensic review record count changed after export.")
if sha256_file(PATHS.input_a) != input_manifest["inputs"]["a"]["sha256"] or sha256_file(PATHS.input_b) != input_manifest["inputs"]["b"]["sha256"]:
    audit_errors.append("An input file changed during execution.")
generator_record = input_manifest["code_assets"]["generator"]
if generator_record is None:
    audit_errors.append("The notebook generator was not available during execution.")
elif not GENERATOR_PATH.is_file() or sha256_file(GENERATOR_PATH) != generator_record["sha256"]:
    audit_errors.append("The notebook generator changed during execution.")
optional_path_lookup = {
    "forensic_review": PATHS.forensic_review_input,
    "match_review": PATHS.match_review_input,
    "source_provenance": PATHS.provenance_input,
    "clean_environment_self_reproduction": PATHS.reproduction_input,
}
for key, record in input_manifest["optional_inputs"].items():
    if record is not None:
        path = optional_path_lookup[key]
        if not path.is_file() or sha256_file(path) != record["sha256"]:
            audit_errors.append(f"Optional input changed during execution: {key}.")
if audit_errors:
    raise RuntimeError("Definitive artifact audit failed:\n- " + "\n- ".join(audit_errors))
reloaded_manifest["artifact_hash_audit"] = True
reloaded_manifest["publication_package_complete"] = True
reloaded_manifest["computationally_ready"] = bool(computationally_ready)
reloaded_manifest["submission_ready"] = bool(submission_ready)
atomic_json(reloaded_manifest, PATHS.artifact_dir / "analysis_manifest.json")
print(f"Verified {len(output_paths)} publication artifacts.")

Verified 24 publication artifacts.

In [43]:
## Final package audit: corrections ledger, raw copies, supplement exports, and table S1

FINAL_PACKAGE_AUDIT_ERRORS: list[str] = []

# 1) Corrections ledger (K2-136 d documented source-error correction)
CORRECTIONS_LEDGER = [
    {
        "planet_key": "k2-136 d",
        "observable": "geometric_area_ratio_ppm",
        "column": "pl_rade",
        "issue_type": "unit_error",
        "issue_severity": "corrected_source_error",
        "recorded_value": "1.450 R_Jup",
        "corrected_value": "0.1293603354 R_Jup",
        "resolution": "Source A radius re-interpreted as an Earth-normalized entry and converted to canonical units (1.450 R_earth = 1.450 / 11.209 R_Jup) before the geometric-area-ratio pipeline.",
        "impact": "After correction K2-136 d has factorial width 1.2257 and rank displacement 85 (rank_a 1465 to rank_b 1380); it is not an extreme case and is not forced into the forensic case set.",
        "documentation": "source_provenance.json source_a.derivative_status and source_a.preprocessing_history",
    },
]
corrections_dir = Path("data/corrections")
corrections_dir.mkdir(parents=True, exist_ok=True)
atomic_csv(pd.DataFrame(CORRECTIONS_LEDGER), corrections_dir / "corrections.csv")

# 2) Raw frozen-input copies for journal deposit
raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)
raw_ledger_rows: list[dict[str, Any]] = []
for input_key, source_path in (("a", PATHS.input_a), ("b", PATHS.input_b)):
    target = raw_dir / source_path.name
    shutil.copy2(source_path, target)
    if sha256_file(target) != input_manifest["inputs"][input_key]["sha256"]:
        FINAL_PACKAGE_AUDIT_ERRORS.append(f"Raw copy hash mismatch: {target}")
    raw_ledger_rows.append({
        "key": input_key,
        "file": source_path.name,
        "sha256": sha256_file(target),
        "bytes": target.stat().st_size,
        "source_path": source_path.as_posix(),
    })
atomic_csv(pd.DataFrame(raw_ledger_rows), raw_dir / "SHA256SUMS.csv")

# 3) Supplement exports: forensic tables and table S1 for the 1,115-displacement planet
supplement_dir = Path("data/supplement")
supplement_dir.mkdir(parents=True, exist_ok=True)
for filename in ("forensic_cases.csv", "forensic_review_record.csv"):
    shutil.copy2(PATHS.artifact_dir / filename, supplement_dir / filename)
table_s1 = operational_certificates[[
    "planet_key", "rank_a", "rank_b", "rank_displacement", "source_value_a",
    "source_value_b", "factorial_width", "top_k_status", "best_rank", "worst_rank",
]].copy()
table_s1 = table_s1.sort_values(["rank_displacement", "planet_key"], ascending=[False, True]).reset_index(drop=True)
table_s1_path = supplement_dir / "table_s1_largest_rank_displacements.csv"
atomic_csv(table_s1, table_s1_path)
if table_s1_path.stat().st_size == 0:
    FINAL_PACKAGE_AUDIT_ERRORS.append("Table S1 is empty.")
if table_s1.iloc[0]["planet_key"] != "kepler-458 c" or int(table_s1.iloc[0]["rank_displacement"]) != 1115:
    FINAL_PACKAGE_AUDIT_ERRORS.append("Table S1 does not lead with the 1,115-displacement planet (kepler-458 c).")
supplement_ledger_rows: list[dict[str, Any]] = []
for filename in ("forensic_cases.csv", "forensic_review_record.csv", "table_s1_largest_rank_displacements.csv"):
    path = supplement_dir / filename
    supplement_ledger_rows.append({"file": filename, "sha256": sha256_file(path), "bytes": path.stat().st_size})
atomic_csv(pd.DataFrame(supplement_ledger_rows), supplement_dir / "SHA256SUMS.csv")

# 4) Full-package hash record appended to the manifest, with authoritative status
package_paths = [*output_paths]
package_paths.extend([
    corrections_dir / "corrections.csv",
    raw_dir / "SHA256SUMS.csv",
    raw_dir / PATHS.input_a.name,
    raw_dir / PATHS.input_b.name,
    supplement_dir / "SHA256SUMS.csv",
    *[supplement_dir / name for name in ("forensic_cases.csv", "forensic_review_record.csv", "table_s1_largest_rank_displacements.csv")],
])
for path in package_paths:
    if not path.is_file() or path.stat().st_size == 0:
        FINAL_PACKAGE_AUDIT_ERRORS.append(f"Final package path missing or empty: {path}")

final_package_record = {
    "date_utc": pd.Timestamp.now(tz="UTC").isoformat(),
    "paths": {path.as_posix(): {"sha256": sha256_file(path), "bytes": path.stat().st_size} for path in package_paths},
}
reloaded_manifest["final_package"] = final_package_record
reloaded_manifest["final_package_audit_complete"] = bool(not FINAL_PACKAGE_AUDIT_ERRORS)
reloaded_manifest["final_package_audit_errors"] = list(FINAL_PACKAGE_AUDIT_ERRORS)
if not FINAL_PACKAGE_AUDIT_ERRORS:
    reloaded_manifest["publication_package_complete"] = True
reloaded_manifest["computationally_ready"] = bool(computationally_ready)
reloaded_manifest["submission_ready"] = bool(submission_ready)
atomic_json(reloaded_manifest, PATHS.artifact_dir / "analysis_manifest.json")

final_package_audit_complete = not bool(FINAL_PACKAGE_AUDIT_ERRORS)
submission_ready = computationally_ready and external_reproduction_complete and final_package_audit_complete
reloaded_results = json.loads((PATHS.artifact_dir / "results_summary.json").read_text(encoding="utf-8"))
reloaded_results["status"]["final_package_audit_complete"] = bool(final_package_audit_complete)
reloaded_results["status"]["submission_ready"] = bool(submission_ready)
reloaded_results["status"]["computationally_ready"] = bool(computationally_ready)
atomic_json(reloaded_results, PATHS.artifact_dir / "results_summary.json")

# Re-hash results_summary.json after status update and patch both hash locations
results_path = PATHS.artifact_dir / "results_summary.json"
reloaded_manifest["outputs"][results_path.as_posix()] = {
    "sha256": sha256_file(results_path),
    "bytes": results_path.stat().st_size,
}
if "final_package" in reloaded_manifest and results_path.as_posix() in reloaded_manifest["final_package"].get("paths", {}):
    reloaded_manifest["final_package"]["paths"][results_path.as_posix()] = {
        "sha256": sha256_file(results_path),
        "bytes": results_path.stat().st_size,
    }
atomic_json(reloaded_manifest, PATHS.artifact_dir / "analysis_manifest.json")

if FINAL_PACKAGE_AUDIT_ERRORS:
    raise RuntimeError("Final package audit failed:\n- " + "\n- ".join(FINAL_PACKAGE_AUDIT_ERRORS))
print(f"Final package audit complete: {len(package_paths)} hashed paths; corrections ledger, raw copies, supplement exports, and table S1 written.")

Final package audit complete: 32 hashed paths; corrections ledger, raw copies, supplement exports, and table S1 written.

In [44]:
artifact_hash_audit = not audit_errors
computationally_definitive = all(quality_gates.values()) and artifact_hash_audit
publication_package_complete = artifact_hash_audit
solo_author_forensic_self_audit_complete = priority_zero_review_complete and priority_zero_findings_status == "acceptable"
clean_environment_self_reproduction_passed = reproduction_payload is not None and reproduction_report.major_count == 0 and reproduction_report.passed
external_reproduction_complete = False
computationally_ready = (
    computationally_definitive and solo_author_forensic_self_audit_complete and publication_package_complete
    and provenance_documented and clean_environment_self_reproduction_passed
)
submission_ready = computationally_ready and external_reproduction_complete and final_package_audit_complete
final_status = pd.DataFrame({
    "item": [
        *quality_gates.keys(), "artifact_hash_audit", "computationally_definitive",
        "forensic_case_selection_complete", "priority_zero_review_complete",
        "solo_author_forensic_self_audit_complete", "provenance_documented",
        "clean_environment_self_reproduction_passed", "publication_package_complete",
        "review_mode", "external_reproduction_complete", "final_package_audit_complete",
        "computationally_ready", "submission_ready",
    ],
    "passed": [
        *quality_gates.values(), artifact_hash_audit, computationally_definitive,
        forensic_report.passed, priority_zero_review_complete,
        solo_author_forensic_self_audit_complete, provenance_documented,
        clean_environment_self_reproduction_passed, publication_package_complete,
        CONFIG.is_solo_author, external_reproduction_complete, final_package_audit_complete,
        computationally_ready, submission_ready,
    ],
})
display(final_status)
display(pd.DataFrame({"item": ["priority_zero_findings_status"], "value": [priority_zero_findings_status]}))
print(f"COMPUTATIONAL CERTIFICATION: {'PASS' if computationally_definitive else 'FAIL'}")
publication_blockers = []
if not computationally_definitive:
    publication_blockers.append("automated computational certification failed")
if not priority_zero_review_complete:
    publication_blockers.append("priority-0 forensic reviews are incomplete")
if priority_zero_findings_status == "correction_required":
    publication_blockers.append("a priority-0 review identified an error requiring correction and rerun")
if not provenance_documented:
    publication_blockers.append("source provenance is incomplete")
if not clean_environment_self_reproduction_passed:
    publication_blockers.append("clean-environment self-reproduction is missing")
if not publication_package_complete:
    publication_blockers.append("artifact package audit failed")
if not external_reproduction_complete:
    publication_blockers.append("external independent reproduction is pending")
if not final_package_audit_complete:
    publication_blockers.append("final package audit is incomplete")
if computationally_ready:
    print("READINESS STATUS: COMPUTATIONALLY READY; SOLO-AUTHOR SELF-AUDIT COMPLETE; FINAL PACKAGE AUDIT COMPLETE; EXTERNAL REPRODUCTION PENDING")
else:
    print("READINESS STATUS: NOT COMPUTATIONALLY READY - " + "; ".join(publication_blockers))

                                          item  passed
0                   generator_script_available    True
1                                 raw_schema_a    True
2                                 raw_schema_b    True
3                                  canonical_a    True
4                                  canonical_b    True
5                                tier1_minimum    True
6                              primary_minimum    True
7                          operational_minimum    True
8          operational_all_concordant_transits    True
9          primary_certificates_fully_verified    True
10     operational_certificates_fully_verified    True
11                     robust_ranking_verified    True
12              primary_table_count_consistent    True
13          operational_table_count_consistent    True
14                     physics_reference_tests    True
15                     ranking_reference_tests    True
16               data_contract_reference_tests    True
17             randomized_bound_property_tests    True
18           randomized_ranking_property_tests    True
19       secondary_certificates_fully_verified    True
20             threshold_partitions_consistent    True
21                 threshold_counts_consistent    True
22            forensic_case_selection_complete    True
23                  detection_mapping_complete    True
24      operational_exclusion_count_consistent    True
25               no_blocking_validation_issues    True
26                         artifact_hash_audit    True
27                  computationally_definitive    True
28            forensic_case_selection_complete    True
29               priority_zero_review_complete    True
30    solo_author_forensic_self_audit_complete    True
31                       provenance_documented    True
32  clean_environment_self_reproduction_passed    True
33                publication_package_complete    True
34                                 review_mode    True
35              external_reproduction_complete   False
36                final_package_audit_complete    True
37                       computationally_ready    True
38                            submission_ready   False

                            item       value
0  priority_zero_findings_status  acceptable

COMPUTATIONAL CERTIFICATION: PASS
READINESS STATUS: COMPUTATIONALLY READY; SOLO-AUTHOR SELF-AUDIT COMPLETE; FINAL PACKAGE AUDIT COMPLETE; EXTERNAL REPRODUCTION PENDING

## Limitations and prohibited interpretations

1. Two derivative source artifacts do not span all epistemic or measurement uncertainty.
2. Coordinate-wise hybrid vertices need not correspond to a published complete parameter set.
3. Shared literature means the sources are not independent replications.
4. Complete-case cohorts are selected toward better-characterized systems.
5. The geometric area ratio is not an observed transit depth or full target-priority metric.
6. Mass-dependent results are secondary because mass semantics may differ.
7. Host resampling measures composition sensitivity, not uncertainty about the frozen estimand.
8. Extreme cases require source-provenance interpretation and are not automatically errors.
9. The analysis measures reproducibility under substitution, not truth, causality, or habitability.
10. Observed discrepancies confound catalog curation decisions with the temporal information-epoch difference between sources (Source A extends to ~February 2018; Source B is frozen in March 2026); disentangling these two effects requires access to same-epoch catalog versions.
11. Of the 444 selected forensic cases, only all 113 priority-0 cases received documented self-audit review; the remaining 331 lower-priority cases have not been manually reviewed and their classification is provisional.

## Reproducible conclusion contract

All manuscript numbers must be copied from `results_summary.json` or the four canonical
tables, with the same denominators, population labels, and rounding policy.  A definitive
execution requires a clean kernel and all cells run once in notebook order.

`COMPUTATIONAL CERTIFICATION: PASS` certifies the implemented mathematics, controlled
cohort construction, exhaustive finite-vertex verification, randomized property tests,
robust-ranking logic, deterministic exports, generator availability, and artifact hashes.
`READINESS STATUS: COMPUTATIONALLY READY; SOLO-AUTHOR SELF-AUDIT COMPLETE; FINAL
PACKAGE AUDIT COMPLETE; EXTERNAL REPRODUCTION PENDING` reflects complete source
provenance, documented self-audit review of every priority-0 forensic case with no
unresolved correction-required finding, a clean-environment reproduction using the same
protocol and frozen inputs, certified by the lead author as a solo-author self-audit,
and a completed final package audit covering the raw-input copies, corrections ledger,
supplement exports, and table S1. External independent reproduction remains pending.

These statuses do not establish that either source is correct, do not quantify total
astrophysical uncertainty, do not guarantee peer-review acceptance, and do not replace
scientific judgment about provenance, population selection, or interpretation.

The clean-environment self-reproduction was performed by the lead author (Khaled Tarchi)
using a separate Python environment with identical frozen inputs. This constitutes
self-reproduction, not independent reproduction; independent reproduction requires
verification by an unaffiliated party.